# Pandas

## Basics

In [2]:
import numpy as np
import pandas as pd

### Series

In [6]:
list1 = [10, 20, 30]
dictionary = {1:10, 2:20, 3:30}
arr = np.array([10, 20, 30])
labels = ['a', 'b', 'c']

In [7]:
pd.Series(list1)

0    10
1    20
2    30
dtype: int64

In [8]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [9]:
pd.Series(arr, labels)

a    10
b    20
c    30
dtype: int64

In [11]:
pd.Series(dictionary)

1    10
2    20
3    30
dtype: int64

### Dataframes

#### Creation

In [33]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df1 = pd.DataFrame(data)
df1

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [30]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [31]:
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns =columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

#### Selecting columns

In [24]:
print(df2["Name"])
df2[["Name", "City"]]

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

#### Creating columns

In [40]:
df2["Designation"] = ["Doctor","Eng.","Doctor","Eng."]
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

#### Removing columns

In [ ]:
df2.drop("Designation", axis=1, inplace=True) # If inplace is not set to True, the deletation will only be for current code not for memory.
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

#### Removing rows

In [42]:
df2.drop(0, axis=0)

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [43]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

#### Selecting rows

In [44]:
df2.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [45]:
df2.loc[[0,2]]

    Name  Age      City  Salary
0   John   28  New York   65000
2  Peter   29    Berlin   62000

In [46]:
df2.iloc[1]

Name       Anna
Age          34
City      Paris
Salary    70000
Name: 1, dtype: object

#### Selecting subsets of rows and columns

In [47]:
df2.loc[[0,1]][['Name', 'City']]

   Name      City
0  John  New York
1  Anna     Paris

#### Conditional selection

In [49]:
df2[df2['Age'] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [50]:
df2[(df2["Age"] > 30) & (df2["City"] == "Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000

### Missing Data

#### Finding missing data

In [4]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [5]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [6]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [7]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

#### Removing missing data

In [8]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [9]:
df.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

#### Filling missing data

In [10]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [11]:
values = {'A':0,'B':100,"C":300,'D':400}
df.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

### Merging, Concating, joining dataframes

#### Merging

In [12]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [13]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [14]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [17]:
pd.merge(employees, salaries)             # pd.merge(employees, salaries, on='employee_id', how='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [16]:
pd.merge(employees, salaries, on='employee_id', how='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [18]:
pd.merge(employees, salaries, on='employee_id', how='left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [19]:
pd.merge(employees, salaries, on='employee_id', how='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

#### Concating dataframes

In [20]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [21]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [22]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [23]:
pd.concat([df1, df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [24]:
pd.concat([df1, df2], axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

#### Joining dataframes

In [25]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [26]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [27]:
df2

   score
2     85
3     90
4     75

In [28]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [29]:
df1.join(df2, how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

### Group by & Aggregation

#### Group by

In [30]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [34]:
cat_group = df.groupby('Category')             # Object
cat_group

In [35]:
cat_group = df.groupby('Category')['Sales'].sum()
cat_group

Category
A    570
B    930
Name: Sales, dtype: int64

In [36]:
store_group = df.groupby('Store')['Sales'].sum()
store_group

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [38]:
combine_group = df.groupby(['Category', 'Store'])['Sales'].sum()
combine_group

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

#### Aggregation

In [39]:
df['Sales'].mean()

np.float64(187.5)

In [40]:
df['Sales'].sum()

np.int64(1500)

In [41]:
df['Sales'].min()

np.int64(100)

In [42]:
df['Sales'].max()

np.int64(300)

In [43]:
df['Sales'].count()

np.int64(8)

In [44]:
df['Sales'].std()

np.float64(66.06274074155351)

In [45]:
df['Sales'].median()

np.float64(190.0)

In [46]:
df['Sales'].agg(['mean', 'min', 'max', 'sum', 'count', 'std', 'median'])

mean       187.500000
min        100.000000
max        300.000000
sum       1500.000000
count        8.000000
std         66.062741
median     190.000000
Name: Sales, dtype: float64