# Pandas

## Advanced

In [7]:
import numpy as np
import pandas as pd

### Useful functions

#### Operations on dataframe

##### shift

In [8]:
# shift function moves the values up or down by a specified number.
s = pd.Series(np.arange(5)).shift()    # by default down values by 1.
print(s)
print()

s = s.shift(-1)
print(s)

0    NaN
1    0.0
2    1.0
3    2.0
4    3.0
dtype: float64

0    0.0
1    1.0
2    2.0
3    3.0
4    NaN
dtype: float64

##### printing dataframe as string

In [9]:
df = pd.DataFrame(np.array(np.random.randint(1,100,12)).reshape(4,3), columns=list('ABC'), index=list('abcd'))
print(df.to_string())

    A   B   C
a  21  15  44
b  72  31  49
c  57  98  58
d  99  81  19

#### Operations with time

##### Basic creation of time range

In [10]:
# Using date_range
rng = pd.date_range('2025-01-15', periods=5)
print(rng, '\n')

# Using to_datetime
rng = pd.to_datetime([
    '2025-01-15',
    '2025-01-19',
    '2025-03-10',
    '2025-02-16',
    '2025-01-31'
])
print(rng)

DatetimeIndex(['2025-01-15', '2025-01-16', '2025-01-17', '2025-01-18',
               '2025-01-19'],
              dtype='datetime64[us]', freq='D')

DatetimeIndex(['2025-01-15', '2025-01-19', '2025-03-10', '2025-02-16',
               '2025-01-31'],
              dtype='datetime64[us]', freq=None)

##### freq

In [11]:
# by default = D means 1 day gap
# 2D means 2 days gap
print(pd.date_range('2025-01-15', periods=5, freq='2D'), '\n')

# W for week, ME for month-end, MS for month-start, QE for quarter-end, YE for year-end, h for hour, min for minute, s for second

print(pd.date_range('2025-01-15', periods=5, freq='MS'), '\n')
print(pd.date_range('2025-01-15', periods=5, freq='QE'), '\n')
print(pd.date_range('2025-01-15', periods=5, freq='min'), '\n')

DatetimeIndex(['2025-01-15', '2025-01-17', '2025-01-19', '2025-01-21',
               '2025-01-23'],
              dtype='datetime64[us]', freq='2D')

DatetimeIndex(['2025-02-01', '2025-03-01', '2025-04-01', '2025-05-01',
               '2025-06-01'],
              dtype='datetime64[us]', freq='MS')

DatetimeIndex(['2025-03-31', '2025-06-30', '2025-09-30', '2025-12-31',
               '2026-03-31'],
              dtype='datetime64[us]', freq='QE-DEC')

DatetimeIndex(['2025-01-15 00:00:00', '2025-01-15 00:01:00',
               '2025-01-15 00:02:00', '2025-01-15 00:03:00',
               '2025-01-15 00:04:00'],
              dtype='datetime64[us]', freq='min')

##### resample

In [12]:
# resample is used to convert timestamped data into a new frequency.
# it works in 2 steps - creates new frequency and then applies aggregation
rng = pd.date_range('2025-03-15', periods=12, freq='5D')
ts = pd.Series(np.random.randint(1,101,12), index=rng)
print(ts[:4])

ts = ts.resample('MS').sum()
ts

2025-03-15    13
2025-03-20    72
2025-03-25     9
2025-03-30    25
Freq: 5D, dtype: int32

2025-03-01    119
2025-04-01    287
2025-05-01     47
Freq: MS, dtype: int32

##### tz_localize and tz_convert

First hh:mm:ss shows the time and second hh:mm shows UTC offset for the timezone.

In [13]:
# tz_localize gives a timezone to a time series.
ts2 = ts.tz_localize('UTC')
ts2

2025-03-01 00:00:00+00:00    119
2025-04-01 00:00:00+00:00    287
2025-05-01 00:00:00+00:00     47
Freq: MS, dtype: int32

In [14]:
# tz_convert converts the timezone to another one and shows information of moments related to older one.
ts3 = ts2.tz_convert('Asia/Kolkata')
ts3

2025-03-01 05:30:00+05:30    119
2025-04-01 05:30:00+05:30    287
2025-05-01 05:30:00+05:30     47
dtype: int32

##### BusinessDay

In [15]:
from pandas.tseries.offsets import BusinessDay
from pandas.tseries.offsets import Day

# BusinessDay skipps the weekends (saturday, sunday) and checks only for working days.
# B in freq of date_range uses frequency for Business Days.
date = pd.Timestamp('2025-01-17')
print(date, date.day_name())

print(date + pd.offsets.Day(1), (date + Day(1)).day_name())
print(date + pd.offsets.BusinessDay(), (date + BusinessDay()).day_name())

2025-01-17 00:00:00 Friday
2025-01-18 00:00:00 Saturday
2025-01-20 00:00:00 Monday

In [16]:
# BusinessDay with series
rng = dates = pd.Series(pd.to_datetime([
    "2025-03-06",
    "2025-03-07",
    "2025-03-08",
    "2025-03-09"
]))
dates + BusinessDay()

0   2025-03-07
1   2025-03-10
2   2025-03-10
3   2025-03-10
dtype: datetime64[us]

#### assign method

##### basic assigning

In [17]:
df = pd.DataFrame({
    "Name": ["A", "B", "C"],
    "Age": [20, 25, 30]
})
df

  Name  Age
0    A   20
1    B   25
2    C   30

In [18]:
df = df.assign(City='Ahmedabad')
df

  Name  Age       City
0    A   20  Ahmedabad
1    B   25  Ahmedabad
2    C   30  Ahmedabad

##### multiple columns

In [19]:
df = df.assign(State='Gujarat', Country='India')
df

  Name  Age       City    State Country
0    A   20  Ahmedabad  Gujarat   India
1    B   25  Ahmedabad  Gujarat   India
2    C   30  Ahmedabad  Gujarat   India

##### using another column

In [20]:
df = df.assign(copy_age=df['Age'])
print(df)
del df['copy_age']

  Name  Age       City    State Country  copy_age
0    A   20  Ahmedabad  Gujarat   India        20
1    B   25  Ahmedabad  Gujarat   India        25
2    C   30  Ahmedabad  Gujarat   India        30

In [21]:
df = df.assign(next_year_age=df['Age']+1)
df

  Name  Age       City    State Country  next_year_age
0    A   20  Ahmedabad  Gujarat   India             21
1    B   25  Ahmedabad  Gujarat   India             26
2    C   30  Ahmedabad  Gujarat   India             31

##### boolean assigning

In [22]:
df.assign(Marks=[80,31,92], Result = lambda x: x['Marks'] >= 33)

  Name  Age       City    State Country  next_year_age  Marks  Result
0    A   20  Ahmedabad  Gujarat   India             21     80    True
1    B   25  Ahmedabad  Gujarat   India             26     31   False
2    C   30  Ahmedabad  Gujarat   India             31     92    True

##### method chaining

In [23]:
df = df.assign(Marks=[80,31,92]).assign(Result = lambda x: x['Marks'] >= 33)
df

  Name  Age       City    State Country  next_year_age  Marks  Result
0    A   20  Ahmedabad  Gujarat   India             21     80    True
1    B   25  Ahmedabad  Gujarat   India             26     31   False
2    C   30  Ahmedabad  Gujarat   India             31     92    True

### Categoricals

#### Creating a categorical

In [24]:
df = pd.DataFrame({
    'id': np.arange(1,5),
    'grade': ['A', 'B', 'A', 'C']
})
print(df['grade'], '\n')

# Using astype
df['grade'] = df['grade'].astype('category')
print(df['grade'], '\n')

# Using categorical
df['grade'] = pd.Categorical(['A', 'B', 'A', 'C'])
print(df['grade'])

0    A
1    B
2    A
3    C
Name: grade, dtype: str

0    A
1    B
2    A
3    C
Name: grade, dtype: category
Categories (3, str): ['A', 'B', 'C']

0    A
1    B
2    A
3    C
Name: grade, dtype: category
Categories (3, str): ['A', 'B', 'C']

#### Accessing the information of categorical

In [25]:
df['grade'].dtype

CategoricalDtype(categories=['A', 'B', 'C'], ordered=False, categories_dtype=str)

In [26]:
df['grade'].cat.categories

Index(['A', 'B', 'C'], dtype='str')

In [27]:
df['grade'].cat.codes

0    0
1    1
2    0
3    2
dtype: int8

#### Operations on categories

##### Rename the categories

In [28]:
df['grade'] = df['grade'].cat.rename_categories({
    'A': 'Excellent',
    'B': 'Good',
    'C': 'Medium',
})
df['grade']

0    Excellent
1         Good
2    Excellent
3       Medium
Name: grade, dtype: category
Categories (3, str): ['Excellent', 'Good', 'Medium']

##### Set categories

In [29]:
df['grade'] = df['grade'].cat.set_categories(['Excellent', 'Good', 'Medium', "Bad"])
df['grade']

0    Excellent
1         Good
2    Excellent
3       Medium
Name: grade, dtype: category
Categories (4, str): ['Excellent', 'Good', 'Medium', 'Bad']

##### Remove categories

In [30]:
df['grade'] = df['grade'].cat.remove_categories('Bad')
print(df['grade'])

# If you deleted the category which exists in dataframe, NaN will be at location of element having the deleted category.

# Remove unused categories
df['grade'] = df['grade'].cat.remove_unused_categories()

0    Excellent
1         Good
2    Excellent
3       Medium
Name: grade, dtype: category
Categories (3, str): ['Excellent', 'Good', 'Medium']

##### Ordered categories

In [31]:
df['grade'] = df['grade'].cat.set_categories(['Excellent', 'Good', 'Medium', 'Bad'], ordered=True)
print(df['grade'], '\n')

# You can also compare ordered categoricals.
print(df['grade'][0] < df['grade'][1], '\n')
print(df['grade'] > 'Excellent')

0    Excellent
1         Good
2    Excellent
3       Medium
Name: grade, dtype: category
Categories (4, str): ['Excellent' < 'Good' < 'Medium' < 'Bad']

True

0    False
1     True
2    False
3     True
Name: grade, dtype: bool

#### Sorting

In [32]:
df = df.sort_values(by='grade')
df

   id      grade
0   1  Excellent
2   3  Excellent
1   2       Good
3   4     Medium

#### Adding another categories & Reordering categories order

In [33]:
# You can add new categories. They will be stored at last of categories in ordering.
df['grade'] = df['grade'].cat.add_categories('Very Bad')
print(df['grade'], '\n')

# So we have to reorder to store them in order.
df['grade'] = df['grade'].cat.reorder_categories(['Excellent', 'Good', 'Medium', 'Bad', 'Very Bad'])
print(df['grade'])

0    Excellent
2    Excellent
1         Good
3       Medium
Name: grade, dtype: category
Categories (5, str): ['Excellent' < 'Good' < 'Medium' < 'Bad' < 'Very Bad']

0    Excellent
2    Excellent
1         Good
3       Medium
Name: grade, dtype: category
Categories (5, str): ['Excellent' < 'Good' < 'Medium' < 'Bad' < 'Very Bad']

#### Grouping

In [34]:
df.groupby('grade', observed=False).size()

grade
Excellent    2
Good         1
Medium       1
Bad          0
Very Bad     0
dtype: int64

### Advanced Concepts

#### Boolean Reduction

##### all

In [35]:
df = pd.DataFrame(np.arange(12).reshape(4,3), columns=list('ABC'), index=list('abcd'))

# all() checks whether condition is true for all the elements or not of a row or a column.
print((df > 1).all(), '\n')         # by default, axis=0
print((df > 3).all(axis=1))

A    False
B    False
C     True
dtype: bool

a    False
b    False
c     True
d     True
dtype: bool

##### any

In [36]:
# any() checks whether condition is true for any of the elements or not of a row or a column.
print((df > 1).any(), '\n')
print((df < 1).any())

A    True
B    True
C    True
dtype: bool

A     True
B    False
C    False
dtype: bool

##### empty

In [37]:
df1 = pd.DataFrame()
df2 = pd.DataFrame(columns=list('ABC'), index=list('abcd'))

# empty checks is dataframe empty or not.
print(df1.empty)
print(df2.empty)

True
False

#### Binary comparison methods

In [38]:
# Binary comparison methods compares two operands and returns True or False.
df = pd.DataFrame(np.arange(12).reshape(4,3), columns=list('ABC'), index=list('abcd'))
print(df, '\n')

print(df.eq(5), '\n')
print(df.le(5))

# eq : equals to : ==
# nq : not equals to : !=
# lt : lesser than : <
# gt : greater than : >
# le : lesser than or equals to : <=
# ge : greater than or equals to : >=

   A   B   C
a  0   1   2
b  3   4   5
c  6   7   8
d  9  10  11

       A      B      C
a  False  False  False
b  False  False   True
c  False  False  False
d  False  False  False

       A      B      C
a   True   True   True
b   True   True   True
c  False  False  False
d  False  False  False

### Console display

#### set_option

##### width

In [39]:
df1 = pd.DataFrame(np.array(np.random.randint(10000000,10000000000, 50, dtype='i8')).reshape(2,25))

# pd.set_option('display.width', 500) This statement will set changes permanently for all outputs.
# To change options temperorily, do as below.

with pd.option_context('display.width', 150):
    print(df1)

           0           1           2           3           4           5           6           7           8           9   ...          15  \
0  5302237642  4103176943  7584033674  8940589088  2372328989  9904012244  3509506322  1066118477  2281120059  4996232264  ...  5568105676
1  3616830795  9419099591  3263992975  3740511016  5094048192  5063973429  3012583992  9594426302  3875038568  6149447291  ...  2642099279

           16          17          18          19          20          21          22          23          24
0  9795555333   692899001  4897386120  6115972436  6507900482  3893761620   570749061  7745705162  3215496072
1  5344279766  7261155977  8353135943  7214865671  8987355324  2017761191  1908135289  5031980097   262746583

[2 rows x 25 columns]

##### max_colwidth

In [40]:
df2 = pd.DataFrame({
    "Name": ["Dhvanit", "Rahul"],
    "Description": [
        "This is a very long description about the first person",
        "This is another very long description about the second person"
    ]
})

with pd.option_context("display.max_colwidth", 20):
    print(df2)

      Name          Description
0  Dhvanit  This is a very l...
1    Rahul  This is another ...

##### max_columns

In [41]:
with pd.option_context('display.max_columns', 15):
    print(df1)

           0           1           2           3           4           5   \
0  5302237642  4103176943  7584033674  8940589088  2372328989  9904012244
1  3616830795  9419099591  3263992975  3740511016  5094048192  5063973429

           6   ...          18          19          20          21  \
0  3509506322  ...  4897386120  6115972436  6507900482  3893761620
1  3012583992  ...  8353135943  7214865671  8987355324  2017761191

           22          23          24
0   570749061  7745705162  3215496072
1  1908135289  5031980097   262746583

[2 rows x 25 columns]

##### max_rows

In [42]:
df3 = pd.DataFrame(np.arange(30).reshape(15,2))

with pd.option_context('display.max_rows', 10):
    print(df3)

     0   1
0    0   1
1    2   3
2    4   5
3    6   7
4    8   9
..  ..  ..
10  20  21
11  22  23
12  24  25
13  26  27
14  28  29

[15 rows x 2 columns]

##### expand_frame_repr

In [43]:
# If it's True, output of dataframe can be wrapped if it's not fit in allowed width.
# If it's false, output will be strictly printed in a single horizontal line.

with pd.option_context(
    'display.width', 150,
    'display.expand_frame_repr', True
):
    print(df1)

print('\n----------------------------------------------------------------------------------------------------------------------------------------\n')

with pd.option_context(
    'display.width', 150,
    'display.expand_frame_repr', False
):
    print(df1)

           0           1           2           3           4           5           6           7           8           9   ...          15  \
0  5302237642  4103176943  7584033674  8940589088  2372328989  9904012244  3509506322  1066118477  2281120059  4996232264  ...  5568105676
1  3616830795  9419099591  3263992975  3740511016  5094048192  5063973429  3012583992  9594426302  3875038568  6149447291  ...  2642099279

           16          17          18          19          20          21          22          23          24
0  9795555333   692899001  4897386120  6115972436  6507900482  3893761620   570749061  7745705162  3215496072
1  5344279766  7261155977  8353135943  7214865671  8987355324  2017761191  1908135289  5031980097   262746583

[2 rows x 25 columns]

----------------------------------------------------------------------------------------------------------------------------------------

           0           1           2           3           4           5           6           7           8           9   ...          15          16          17          18          19          20          21          22          23          24
0  5302237642  4103176943  7584033674  8940589088  2372328989  9904012244  3509506322  1066118477  2281120059  4996232264  ...  5568105676  9795555333   692899001  4897386120  6115972436  6507900482  3893761620   570749061  7745705162  3215496072
1  3616830795  9419099591  3263992975  3740511016  5094048192  5063973429  3012583992  9594426302  3875038568  6149447291  ...  2642099279  5344279766  7261155977  8353135943  7214865671  8987355324  2017761191  1908135289  5031980097   262746583

[2 rows x 25 columns]

#### get_option

In [44]:
# We can print values of any display option using get_option.

print(pd.get_option("display.width"))
print(pd.get_option("display.max_columns"))
print(pd.get_option("display.max_rows"))
print(pd.get_option("display.max_colwidth"))
print(pd.get_option("display.expand_frame_repr"))

80
20
60
50
True