# Pandas

## Basics

In [81]:
import numpy as np
import pandas as pd

### Dataframes

#### Series

In [82]:
list1 = [10, 20, 30]
dictionary = {1:10, 2:20, 3:30}
arr = np.array([10, 20, 30])
labels = ['a', 'b', 'c']

print(pd.Series(list1), '\n')
print(pd.Series(arr), '\n')
print(pd.Series(arr, labels), '\n')
print(pd.Series(dictionary))

0    10
1    20
2    30
dtype: int64

0    10
1    20
2    30
dtype: int64

a    10
b    20
c    30
dtype: int64

1    10
2    20
3    30
dtype: int64

#### Creation of Dataframes

##### Using Dictionary

In [83]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

##### Using List

In [84]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
print(df2)
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list, columns =columns)
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

##### Use of date_range() and index

In [85]:
dates = pd.date_range("2025-01-20", periods=6)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

                   A         B         C         D
2025-01-20 -0.342301 -0.272076  1.672745 -1.565669
2025-01-21 -0.338846  0.039369  0.601946 -2.444515
2025-01-22  2.153489  0.739198 -1.072077 -0.782913
2025-01-23  1.860932 -1.173287 -0.365031 -0.621434
2025-01-24  0.693002 -1.040816 -0.209102 -0.640821
2025-01-25  0.172673  0.488234 -1.314023 -0.356888

#### Viewing Data

##### Header and Footer of Dataframe

In [86]:
print(df.head(), '\n')
print(df.tail(3))

                   A         B         C         D
2025-01-20 -0.342301 -0.272076  1.672745 -1.565669
2025-01-21 -0.338846  0.039369  0.601946 -2.444515
2025-01-22  2.153489  0.739198 -1.072077 -0.782913
2025-01-23  1.860932 -1.173287 -0.365031 -0.621434
2025-01-24  0.693002 -1.040816 -0.209102 -0.640821

                   A         B         C         D
2025-01-23  1.860932 -1.173287 -0.365031 -0.621434
2025-01-24  0.693002 -1.040816 -0.209102 -0.640821
2025-01-25  0.172673  0.488234 -1.314023 -0.356888

##### Information about Dataframe

In [87]:
print(df.index, '\n')
print(df.columns, '\n')
print(df.dtypes)

DatetimeIndex(['2025-01-20', '2025-01-21', '2025-01-22', '2025-01-23',
               '2025-01-24', '2025-01-25'],
              dtype='datetime64[us]', freq='D')

Index(['A', 'B', 'C', 'D'], dtype='str')

A    float64
B    float64
C    float64
D    float64
dtype: object

In [88]:
print(df.info(), '\n')
print(df.describe())

<class 'pandas.DataFrame'>
DatetimeIndex: 6 entries, 2025-01-20 to 2025-01-25
Freq: D
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       6 non-null      float64
 1   B       6 non-null      float64
 2   C       6 non-null      float64
 3   D       6 non-null      float64
dtypes: float64(4)
memory usage: 240.0 bytes
None

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.699825 -0.203229 -0.114257 -1.068707
std    1.086656  0.783894  1.107706  0.788838
min   -0.342301 -1.173287 -1.314023 -2.444515
25%   -0.210967 -0.848631 -0.895315 -1.369980
50%    0.432837 -0.116353 -0.287067 -0.711867
75%    1.568950  0.376018  0.399184 -0.626280
max    2.153489  0.739198  1.672745 -0.356888

##### Transformation of Dataframe

In [89]:
print(df.T, '\n')
print(df.to_numpy())

   2025-01-20  2025-01-21  2025-01-22  2025-01-23  2025-01-24  2025-01-25
A   -0.342301   -0.338846    2.153489    1.860932    0.693002    0.172673
B   -0.272076    0.039369    0.739198   -1.173287   -1.040816    0.488234
C    1.672745    0.601946   -1.072077   -0.365031   -0.209102   -1.314023
D   -1.565669   -2.444515   -0.782913   -0.621434   -0.640821   -0.356888

[[-0.34230064 -0.27207561  1.67274489 -1.56566905]
 [-0.33884646  0.03936924  0.60194569 -2.44451524]
 [ 2.15348931  0.73919811 -1.07207695 -0.78291272]
 [ 1.8609321  -1.17328661 -0.36503084 -0.62143359]
 [ 0.69300214 -1.04081559 -0.2091023  -0.6408207 ]
 [ 0.17267256  0.48823365 -1.31402336 -0.35688806]]

##### Sorting in Dataframe

In [90]:
df.sort_index(axis=1, ascending=False)

                   D         C         B         A
2025-01-20 -1.565669  1.672745 -0.272076 -0.342301
2025-01-21 -2.444515  0.601946  0.039369 -0.338846
2025-01-22 -0.782913 -1.072077  0.739198  2.153489
2025-01-23 -0.621434 -0.365031 -1.173287  1.860932
2025-01-24 -0.640821 -0.209102 -1.040816  0.693002
2025-01-25 -0.356888 -1.314023  0.488234  0.172673

In [91]:
df.sort_values(by="B")

                   A         B         C         D
2025-01-23  1.860932 -1.173287 -0.365031 -0.621434
2025-01-24  0.693002 -1.040816 -0.209102 -0.640821
2025-01-20 -0.342301 -0.272076  1.672745 -1.565669
2025-01-21 -0.338846  0.039369  0.601946 -2.444515
2025-01-25  0.172673  0.488234 -1.314023 -0.356888
2025-01-22  2.153489  0.739198 -1.072077 -0.782913

### Selection

##### Getitem ([])

In [92]:
# Column
df['A']

2025-01-20   -0.342301
2025-01-21   -0.338846
2025-01-22    2.153489
2025-01-23    1.860932
2025-01-24    0.693002
2025-01-25    0.172673
Freq: D, Name: A, dtype: float64

In [93]:
# Multiple columns
df[['A', 'B']]

                   A         B
2025-01-20 -0.342301 -0.272076
2025-01-21 -0.338846  0.039369
2025-01-22  2.153489  0.739198
2025-01-23  1.860932 -1.173287
2025-01-24  0.693002 -1.040816
2025-01-25  0.172673  0.488234

In [94]:
# rows
df[0:3]

                   A         B         C         D
2025-01-20 -0.342301 -0.272076  1.672745 -1.565669
2025-01-21 -0.338846  0.039369  0.601946 -2.444515
2025-01-22  2.153489  0.739198 -1.072077 -0.782913

##### Selection by label

In [95]:
# row
df.loc[dates[0]]

A   -0.342301
B   -0.272076
C    1.672745
D   -1.565669
Name: 2025-01-20 00:00:00, dtype: float64

In [96]:
# all rows with only 'A' and 'B' column
df.loc[:, ['A', 'B']]

                   A         B
2025-01-20 -0.342301 -0.272076
2025-01-21 -0.338846  0.039369
2025-01-22  2.153489  0.739198
2025-01-23  1.860932 -1.173287
2025-01-24  0.693002 -1.040816
2025-01-25  0.172673  0.488234

In [97]:
# subset of selected rows and columns
df.loc['2025-01-22':'2025-01-25', ['A', 'B']]

                   A         B
2025-01-22  2.153489  0.739198
2025-01-23  1.860932 -1.173287
2025-01-24  0.693002 -1.040816
2025-01-25  0.172673  0.488234

In [98]:
# Single element
print(df.loc[dates[0], 'A'])
print(df.at[dates[0], 'A'])

-0.3423006427250351
-0.3423006427250351

##### Selection by position

In [99]:
# row
df.iloc[2]

A    2.153489
B    0.739198
C   -1.072077
D   -0.782913
Name: 2025-01-22 00:00:00, dtype: float64

In [100]:
# subset
df.iloc[1:3, :2]

                   A         B
2025-01-21 -0.338846  0.039369
2025-01-22  2.153489  0.739198

In [101]:
# list of integer position locations
df.iloc[[1, 2, 4], [1, 3]]

                   B         D
2025-01-21  0.039369 -2.444515
2025-01-22  0.739198 -0.782913
2025-01-24 -1.040816 -0.640821

In [102]:
# Single element
print(df.iloc[1, 2])
print(df.iat[1, 2])

0.6019456911708119
0.6019456911708119

##### Boolean indexing

In [103]:
#Select rows where df.A is greater than 0.
df[df['A'] > 0]

                   A         B         C         D
2025-01-22  2.153489  0.739198 -1.072077 -0.782913
2025-01-23  1.860932 -1.173287 -0.365031 -0.621434
2025-01-24  0.693002 -1.040816 -0.209102 -0.640821
2025-01-25  0.172673  0.488234 -1.314023 -0.356888

In [104]:
#Selecting values from a DataFrame where a boolean condition is met:
df[df > 0]

                   A         B         C   D
2025-01-20       NaN       NaN  1.672745 NaN
2025-01-21       NaN  0.039369  0.601946 NaN
2025-01-22  2.153489  0.739198       NaN NaN
2025-01-23  1.860932       NaN       NaN NaN
2025-01-24  0.693002       NaN       NaN NaN
2025-01-25  0.172673  0.488234       NaN NaN

### Setting

##### Setting new column

In [105]:
s1 = pd.Series([1,2,3,4,5,6], index=pd.date_range('2025-01-20', periods=6))
df['F'] = s1
df.head(3)

                   A         B         C         D  F
2025-01-20 -0.342301 -0.272076  1.672745 -1.565669  1
2025-01-21 -0.338846  0.039369  0.601946 -2.444515  2
2025-01-22  2.153489  0.739198 -1.072077 -0.782913  3

##### Modifying column

In [106]:
df['D'] = np.array([5] * len(df))
df.head(3)

                   A         B         C  D  F
2025-01-20 -0.342301 -0.272076  1.672745  5  1
2025-01-21 -0.338846  0.039369  0.601946  5  2
2025-01-22  2.153489  0.739198 -1.072077  5  3

##### Setting new element

In [107]:
df.at[dates[0], 'A'] = 0
df.iat[0, 1] = 0
df.iloc[0]

A    0.000000
B    0.000000
C    1.672745
D    5.000000
F    1.000000
Name: 2025-01-20 00:00:00, dtype: float64

##### Setting new row

In [108]:
df.loc[pd.Timestamp('2025-01-29')] = np.append(np.random.randn(3), [5, 7])
df.tail(3)
# You can modify row like this also.

                   A         B         C    D    F
2025-01-24  0.693002 -1.040816 -0.209102  5.0  5.0
2025-01-25  0.172673  0.488234 -1.314023  5.0  6.0
2025-01-29  0.172198  1.044306 -0.694035  5.0  7.0

##### Modifying the index of row

In [109]:
df.rename(index={pd.Timestamp('2025-01-29'): pd.Timestamp('2025-01-26')}, inplace=True)
df.tail(3)

                   A         B         C    D    F
2025-01-24  0.693002 -1.040816 -0.209102  5.0  5.0
2025-01-25  0.172673  0.488234 -1.314023  5.0  6.0
2025-01-26  0.172198  1.044306 -0.694035  5.0  7.0

##### Removing column

In [110]:
df.drop('A', axis=1).head(3)

# df.drop('A', axis=1, inplace=True) will delete it permanently from memory.

                   B         C    D    F
2025-01-20  0.000000  1.672745  5.0  1.0
2025-01-21  0.039369  0.601946  5.0  2.0
2025-01-22  0.739198 -1.072077  5.0  3.0

##### Removing row

In [111]:
df.drop('2025-01-24')

                   A         B         C    D    F
2025-01-20  0.000000  0.000000  1.672745  5.0  1.0
2025-01-21 -0.338846  0.039369  0.601946  5.0  2.0
2025-01-22  2.153489  0.739198 -1.072077  5.0  3.0
2025-01-23  1.860932 -1.173287 -0.365031  5.0  4.0
2025-01-25  0.172673  0.488234 -1.314023  5.0  6.0
2025-01-26  0.172198  1.044306 -0.694035  5.0  7.0

### Missing Data

#### Finding missing data

In [112]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df2 = pd.DataFrame(data)
df2

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [113]:
df2.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [114]:
df2.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [115]:
df2.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

#### Removing missing data

In [116]:
df2.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [117]:
df2.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

#### Filling missing data

In [118]:
df2.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [119]:
values = {'A':0,'B':100,"C":300,'D':400}
df2.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

### Merge and Grouping

#### Merging

In [120]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [121]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [122]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [123]:
pd.merge(employees, salaries)             # pd.merge(employees, salaries, on='employee_id', how='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [124]:
pd.merge(employees, salaries, on='employee_id', how='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [125]:
pd.merge(employees, salaries, on='employee_id', how='left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [126]:
pd.merge(employees, salaries, on='employee_id', how='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

#### Concating

In [127]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [128]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [129]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [130]:
pd.concat([df1, df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [131]:
pd.concat([df1, df2], axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

#### Joining

In [132]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

print(df1, df2, sep='\n\n')

      name
1    Alice
2      Bob
3  Charlie

   score
2     85
3     90
4     75

In [133]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [134]:
df1.join(df2, how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

#### Grouping

In [135]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df2 = pd.DataFrame(data)
df2

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [136]:
cat_group = df2.groupby('Category')
cat_group

In [137]:
cat_group = df2.groupby('Category')['Sales'].sum()
cat_group

Category
A    570
B    930
Name: Sales, dtype: int64

In [138]:
store_group = df2.groupby('Store')['Sales'].sum()
store_group

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [139]:
combine_group = df2.groupby(['Category', 'Store'])['Sales'].sum()
combine_group

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

### Stack and Pivot Tables

#### Stack & Unstack

In [140]:
arrays = [
   ["bar", "bar", "baz", "baz"],
   ["one", "two", "one", "two"],
]

index = pd.MultiIndex.from_arrays(arrays, names=["first", "second"])
df = pd.DataFrame(np.random.randn(4, 2), index=index, columns=["A", "B"])
print(df, '\n')

stacked = df.stack()
print(stacked)

                     A         B
first second
bar   one    -0.022547  0.168907
      two    -1.613008  0.482771
baz   one     0.547533  0.781958
      two    -1.405888  0.258591

first  second
bar    one     A   -0.022547
               B    0.168907
       two     A   -1.613008
               B    0.482771
baz    one     A    0.547533
               B    0.781958
       two     A   -1.405888
               B    0.258591
dtype: float64

In [141]:
unstacked = stacked.unstack()
print(unstacked, '\n')

unstacked = stacked.unstack(0)
print(unstacked, '\n')

unstacked = stacked.unstack(1)
print(unstacked)

                     A         B
first second
bar   one    -0.022547  0.168907
      two    -1.613008  0.482771
baz   one     0.547533  0.781958
      two    -1.405888  0.258591

first          bar       baz
second
one    A -0.022547  0.547533
       B  0.168907  0.781958
two    A -1.613008 -1.405888
       B  0.482771  0.258591

second        one       two
first
bar   A -0.022547 -1.613008
      B  0.168907  0.482771
baz   A  0.547533 -1.405888
      B  0.781958  0.258591

#### Pivot tables

In [142]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df2 = pd.DataFrame(data)

df2['Month'] = df2['Date'].dt.month_name()
df2['Quarter'] = 'Q' + df2['Date'].dt.quarter.astype(str)
df2

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    896     46   John  January      Q1
1  2023-01-02       B   West    186     39   Mary  January      Q1
2  2023-01-03       C  North    925     10    Bob  January      Q1
3  2023-01-04       D  South    379     76  Alice  January      Q1
4  2023-01-05       A   East    820     94   John  January      Q1
5  2023-01-06       B   West    663     79   Mary  January      Q1
6  2023-01-07       C  North    326     90    Bob  January      Q1
7  2023-01-08       D  South    991     56  Alice  January      Q1
8  2023-01-09       A   East    751     50   John  January      Q1
9  2023-01-10       B   West    207     82   Mary  January      Q1
10 2023-01-11       C  North    457     77    Bob  January      Q1
11 2023-01-12       D  South    613     69  Alice  January      Q1
12 2023-01-13       A   East    680     40   John  January      Q1
13 2023-01-14       B   West    703     11   Mary  January      Q1
14 2023-01-15       C  North    226     12    Bob  January      Q1
15 2023-01-16       D  South    369     46  Alice  January      Q1
16 2023-01-17       A   East    658     23   John  January      Q1
17 2023-01-18       B   West    746     68   Mary  January      Q1
18 2023-01-19       C  North    934     80    Bob  January      Q1
19 2023-01-20       D  South    108     99  Alice  January      Q1

In [143]:
pivot_table_1 = pd.pivot_table(data=df2, values='Sales', index='Region', columns='Product')
pivot_table_1

Product      A      B      C      D
Region
East     761.0    NaN    NaN    NaN
North      NaN    NaN  573.6    NaN
South      NaN    NaN    NaN  492.0
West       NaN  501.0    NaN    NaN

In [144]:
pivot_table_2 = pd.pivot_table(data=df2, values=['Sales', 'Units'], index='Region', columns='Product')
pivot_table_2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     761.0    NaN    NaN    NaN  50.6   NaN   NaN   NaN
North      NaN    NaN  573.6    NaN   NaN   NaN  53.8   NaN
South      NaN    NaN    NaN  492.0   NaN   NaN   NaN  69.2
West       NaN  501.0    NaN    NaN   NaN  55.8   NaN   NaN

#### Crosstabs

In [145]:
crosstab_1 = pd.crosstab(df2['Region'], df2['Product'])
crosstab_1

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

### Operations

#### Dataframes basic operations

##### Aggregation functions

In [146]:
df1 = pd.DataFrame({
    'Id': [1, 2, 3, 4, 5],
    'Price': [600, 720, 590, 650, 700],
    'Sales': [1000, 1000, 1200, 900, 1000]
})
df1

   Id  Price  Sales
0   1    600   1000
1   2    720   1000
2   3    590   1200
3   4    650    900
4   5    700   1000

In [147]:
print('Mean : ', df1['Sales'].mean())
print('Sum : ', df1['Sales'].sum())
print('Min : ', df1['Sales'].min())
print('Max : ', df1['Sales'].max())
print('Count : ', df1['Sales'].count())
print('Std : ', df1['Sales'].std())
print('Median : ', df1['Sales'].median())

Mean :  1020.0
Sum :  5100
Min :  900
Max :  1200
Count :  5
Std :  109.54451150103323
Median :  1000.0

In [148]:
df1['Sales'].agg(['mean', 'min', 'max', 'sum', 'count', 'std', 'median'])

mean      1020.000000
min        900.000000
max       1200.000000
sum       5100.000000
count        5.000000
std        109.544512
median    1000.000000
Name: Sales, dtype: float64

##### Basic Operations

In [149]:
df2 = df1['Id'] + 10
df2

0    11
1    12
2    13
3    14
4    15
Name: Id, dtype: int64

#### Applying functions

In [150]:
def square(x):
    return x**2

In [151]:
df1['Id'].apply(square)

0     1
1     4
2     9
3    16
4    25
Name: Id, dtype: int64

In [152]:
df1['raw Id'] = df1['Id'].apply(lambda x: x**3)
df1

   Id  Price  Sales  raw Id
0   1    600   1000       1
1   2    720   1000       8
2   3    590   1200      27
3   4    650    900      64
4   5    700   1000     125