# Pandas

## Basics

In [1898]:
import numpy as np
import pandas as pd

### Dataframes

#### Series

In [1899]:
list1 = [10, 20, 30]
dictionary = {1:10, 2:20, 3:30}
arr = np.array([10, 20, 30])
labels = ['a', 'b', 'c']

print(pd.Series(list1), '\n')
print(pd.Series(arr), '\n')
print(pd.Series(arr, labels), '\n')
print(pd.Series(dictionary))

0    10
1    20
2    30
dtype: int64

0    10
1    20
2    30
dtype: int64

a    10
b    20
c    30
dtype: int64

1    10
2    20
3    30
dtype: int64

#### Creation of Dataframes

##### Using Dictionary

In [1900]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

##### Using List

In [1901]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
print(df2)
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list, columns =columns)
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

##### Use of date_range() and index

In [1902]:
dates = pd.date_range("2025-01-20", periods=6)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

                   A         B         C         D
2025-01-20  1.757782  1.234251  1.532931 -1.530511
2025-01-21  0.223479 -2.142847  0.187546 -0.670997
2025-01-22  0.271752 -0.246751 -0.440958 -0.106316
2025-01-23  2.011020  0.550251 -0.849514 -0.173771
2025-01-24 -0.759371  0.026775 -0.608402 -0.482232
2025-01-25  0.598352 -0.298300 -1.781356 -0.605057

#### Viewing Data

##### Header and Footer of Dataframe

In [1903]:
print(df.head(), '\n')
print(df.tail(3))

                   A         B         C         D
2025-01-20  1.757782  1.234251  1.532931 -1.530511
2025-01-21  0.223479 -2.142847  0.187546 -0.670997
2025-01-22  0.271752 -0.246751 -0.440958 -0.106316
2025-01-23  2.011020  0.550251 -0.849514 -0.173771
2025-01-24 -0.759371  0.026775 -0.608402 -0.482232

                   A         B         C         D
2025-01-23  2.011020  0.550251 -0.849514 -0.173771
2025-01-24 -0.759371  0.026775 -0.608402 -0.482232
2025-01-25  0.598352 -0.298300 -1.781356 -0.605057

##### Information about Dataframe

In [1904]:
print(df.index, '\n')
print(df.columns, '\n')
print(df.dtypes)

DatetimeIndex(['2025-01-20', '2025-01-21', '2025-01-22', '2025-01-23',
               '2025-01-24', '2025-01-25'],
              dtype='datetime64[us]', freq='D')

Index(['A', 'B', 'C', 'D'], dtype='str')

A    float64
B    float64
C    float64
D    float64
dtype: object

In [1905]:
print(df.info(), '\n')
print(df.describe())

<class 'pandas.DataFrame'>
DatetimeIndex: 6 entries, 2025-01-20 to 2025-01-25
Freq: D
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       6 non-null      float64
 1   B       6 non-null      float64
 2   C       6 non-null      float64
 3   D       6 non-null      float64
dtypes: float64(4)
memory usage: 240.0 bytes
None

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.683836 -0.146103 -0.326625 -0.594814
std    1.037948  1.134941  1.113952  0.511863
min   -0.759371 -2.142847 -1.781356 -1.530511
25%    0.235547 -0.285413 -0.789236 -0.654512
50%    0.435052 -0.109988 -0.524680 -0.543644
75%    1.467925  0.419382  0.030420 -0.250886
max    2.011020  1.234251  1.532931 -0.106316

##### Transformation of Dataframe

In [1906]:
print(df.T, '\n')
print(df.to_numpy())

   2025-01-20  2025-01-21  2025-01-22  2025-01-23  2025-01-24  2025-01-25
A    1.757782    0.223479    0.271752    2.011020   -0.759371    0.598352
B    1.234251   -2.142847   -0.246751    0.550251    0.026775   -0.298300
C    1.532931    0.187546   -0.440958   -0.849514   -0.608402   -1.781356
D   -1.530511   -0.670997   -0.106316   -0.173771   -0.482232   -0.605057

[[ 1.75778231  1.23425134  1.53293116 -1.53051116]
 [ 0.22347877 -2.14284664  0.18754563 -0.6709968 ]
 [ 0.27175182 -0.24675107 -0.44095775 -0.10631614]
 [ 2.01102037  0.55025131 -0.84951357 -0.17377055]
 [-0.75937147  0.02677519 -0.60840227 -0.48223226]
 [ 0.59835246 -0.29830028 -1.78135561 -0.60505667]]

##### Sorting in Dataframe

In [1907]:
df.sort_index(axis=1, ascending=False)

                   D         C         B         A
2025-01-20 -1.530511  1.532931  1.234251  1.757782
2025-01-21 -0.670997  0.187546 -2.142847  0.223479
2025-01-22 -0.106316 -0.440958 -0.246751  0.271752
2025-01-23 -0.173771 -0.849514  0.550251  2.011020
2025-01-24 -0.482232 -0.608402  0.026775 -0.759371
2025-01-25 -0.605057 -1.781356 -0.298300  0.598352

In [1908]:
df.sort_values(by="B")

                   A         B         C         D
2025-01-21  0.223479 -2.142847  0.187546 -0.670997
2025-01-25  0.598352 -0.298300 -1.781356 -0.605057
2025-01-22  0.271752 -0.246751 -0.440958 -0.106316
2025-01-24 -0.759371  0.026775 -0.608402 -0.482232
2025-01-23  2.011020  0.550251 -0.849514 -0.173771
2025-01-20  1.757782  1.234251  1.532931 -1.530511

#### Selection & Setting

##### Getitem ([])

In [1909]:
# Column
df['A']

2025-01-20    1.757782
2025-01-21    0.223479
2025-01-22    0.271752
2025-01-23    2.011020
2025-01-24   -0.759371
2025-01-25    0.598352
Freq: D, Name: A, dtype: float64

In [1910]:
# Multiple columns
df[['A', 'B']]

                   A         B
2025-01-20  1.757782  1.234251
2025-01-21  0.223479 -2.142847
2025-01-22  0.271752 -0.246751
2025-01-23  2.011020  0.550251
2025-01-24 -0.759371  0.026775
2025-01-25  0.598352 -0.298300

In [1911]:
# rows
df[0:3]

                   A         B         C         D
2025-01-20  1.757782  1.234251  1.532931 -1.530511
2025-01-21  0.223479 -2.142847  0.187546 -0.670997
2025-01-22  0.271752 -0.246751 -0.440958 -0.106316

##### Selection by label

In [1912]:
# row
df.loc[dates[0]]

A    1.757782
B    1.234251
C    1.532931
D   -1.530511
Name: 2025-01-20 00:00:00, dtype: float64

In [1913]:
# all rows with only 'A' and 'B' column
df.loc[:, ['A', 'B']]

                   A         B
2025-01-20  1.757782  1.234251
2025-01-21  0.223479 -2.142847
2025-01-22  0.271752 -0.246751
2025-01-23  2.011020  0.550251
2025-01-24 -0.759371  0.026775
2025-01-25  0.598352 -0.298300

In [1914]:
# subset of selected rows and columns
df.loc['2025-01-22':'2025-01-25', ['A', 'B']]

                   A         B
2025-01-22  0.271752 -0.246751
2025-01-23  2.011020  0.550251
2025-01-24 -0.759371  0.026775
2025-01-25  0.598352 -0.298300

In [1915]:
# Single element
print(df.loc[dates[0], 'A'])
print(df.at[dates[0], 'A'])

1.7577823053450814
1.7577823053450814

##### Selection by position

In [1916]:
# row
df.iloc[2]

A    0.271752
B   -0.246751
C   -0.440958
D   -0.106316
Name: 2025-01-22 00:00:00, dtype: float64

In [1917]:
# subset
df.iloc[1:3, :2]

                   A         B
2025-01-21  0.223479 -2.142847
2025-01-22  0.271752 -0.246751

In [1918]:
# list of integer position locations
df.iloc[[1, 2, 4], [1, 3]]

                   B         D
2025-01-21 -2.142847 -0.670997
2025-01-22 -0.246751 -0.106316
2025-01-24  0.026775 -0.482232

In [1919]:
# Single element
print(df.iloc[1, 2])
print(df.iat[1, 2])

0.18754562881220319
0.18754562881220319

##### Boolean indexing

In [1920]:
#Select rows where df.A is greater than 0.
df[df['A'] > 0]

                   A         B         C         D
2025-01-20  1.757782  1.234251  1.532931 -1.530511
2025-01-21  0.223479 -2.142847  0.187546 -0.670997
2025-01-22  0.271752 -0.246751 -0.440958 -0.106316
2025-01-23  2.011020  0.550251 -0.849514 -0.173771
2025-01-25  0.598352 -0.298300 -1.781356 -0.605057

In [1921]:
#Selecting values from a DataFrame where a boolean condition is met:
df[df > 0]

                   A         B         C   D
2025-01-20  1.757782  1.234251  1.532931 NaN
2025-01-21  0.223479       NaN  0.187546 NaN
2025-01-22  0.271752       NaN       NaN NaN
2025-01-23  2.011020  0.550251       NaN NaN
2025-01-24       NaN  0.026775       NaN NaN
2025-01-25  0.598352       NaN       NaN NaN

##### Setting

###### Setting new column

In [1922]:
s1 = pd.Series([1,2,3,4,5,6], index=pd.date_range('2025-01-20', periods=6))
df['F'] = s1
df.head(3)

                   A         B         C         D  F
2025-01-20  1.757782  1.234251  1.532931 -1.530511  1
2025-01-21  0.223479 -2.142847  0.187546 -0.670997  2
2025-01-22  0.271752 -0.246751 -0.440958 -0.106316  3

###### Modifying column

In [1923]:
df['D'] = np.array([5] * len(df))
df.head(3)

                   A         B         C  D  F
2025-01-20  1.757782  1.234251  1.532931  5  1
2025-01-21  0.223479 -2.142847  0.187546  5  2
2025-01-22  0.271752 -0.246751 -0.440958  5  3

###### Setting new element

In [1924]:
df.at[dates[0], 'A'] = 0
df.iat[0, 1] = 0
df.iloc[0]

A    0.000000
B    0.000000
C    1.532931
D    5.000000
F    1.000000
Name: 2025-01-20 00:00:00, dtype: float64

###### Setting new row

In [1925]:
df.loc[pd.Timestamp('2025-01-29')] = np.append(np.random.randn(3), [5, 7])
df.tail(3)
# You can modify row like this also.

                   A         B         C    D    F
2025-01-24 -0.759371  0.026775 -0.608402  5.0  5.0
2025-01-25  0.598352 -0.298300 -1.781356  5.0  6.0
2025-01-29  1.372529  0.170667 -0.617636  5.0  7.0

###### Modifying the index of row

In [1926]:
df.rename(index={pd.Timestamp('2025-01-29'): pd.Timestamp('2025-01-26')}, inplace=True)
df.tail(3)

                   A         B         C    D    F
2025-01-24 -0.759371  0.026775 -0.608402  5.0  5.0
2025-01-25  0.598352 -0.298300 -1.781356  5.0  6.0
2025-01-26  1.372529  0.170667 -0.617636  5.0  7.0

###### Removing column

In [1927]:
df.drop('A', axis=1).head(3)

# df.drop('A', axis=1, inplace=True) will delete it permanently from memory.

                   B         C    D    F
2025-01-20  0.000000  1.532931  5.0  1.0
2025-01-21 -2.142847  0.187546  5.0  2.0
2025-01-22 -0.246751 -0.440958  5.0  3.0

###### Removing row

In [1928]:
df.drop('2025-01-24')

                   A         B         C    D    F
2025-01-20  0.000000  0.000000  1.532931  5.0  1.0
2025-01-21  0.223479 -2.142847  0.187546  5.0  2.0
2025-01-22  0.271752 -0.246751 -0.440958  5.0  3.0
2025-01-23  2.011020  0.550251 -0.849514  5.0  4.0
2025-01-25  0.598352 -0.298300 -1.781356  5.0  6.0
2025-01-26  1.372529  0.170667 -0.617636  5.0  7.0

### Missing Data

#### Finding missing data

In [1929]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df2 = pd.DataFrame(data)
df2

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [1930]:
df2.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [1931]:
df2.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [1932]:
df2.isna().sum()

c:\full stack web developement\Repository\Python AI\myvenv\Lib\site-packages\IPython\core\displayhook.py:291: UserWarning: Output cache limit (currently 1000 entries) hit.
Flushing oldest 200 entries.
  warn('Output cache limit (currently {sz} entries) hit.\n'

A    1
B    0
C    2
D    3
dtype: int64

#### Removing missing data

In [1933]:
df2.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [1934]:
df2.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

#### Filling missing data

In [1935]:
df2.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [1936]:
values = {'A':0,'B':100,"C":300,'D':400}
df2.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

### Merging, Concating, Joining Dataframes

#### Merging

In [1937]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [1938]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [1939]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [1940]:
pd.merge(employees, salaries)             # pd.merge(employees, salaries, on='employee_id', how='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [1941]:
pd.merge(employees, salaries, on='employee_id', how='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [1942]:
pd.merge(employees, salaries, on='employee_id', how='left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [1943]:
pd.merge(employees, salaries, on='employee_id', how='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

#### Concating dataframes

In [1944]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [1945]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [1946]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [1947]:
pd.concat([df1, df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [1948]:
pd.concat([df1, df2], axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

#### Joining dataframes

In [1949]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [1950]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [1951]:
df2

   score
2     85
3     90
4     75

In [1952]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [1953]:
df1.join(df2, how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

### Group by & Aggregation

#### Group by

In [1954]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df2 = pd.DataFrame(data)
df2

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [1955]:
cat_group = df2.groupby('Category')             # Object
cat_group

In [1956]:
cat_group = df2.groupby('Category')['Sales'].sum()
cat_group

Category
A    570
B    930
Name: Sales, dtype: int64

In [1957]:
store_group = df2.groupby('Store')['Sales'].sum()
store_group

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [1958]:
combine_group = df2.groupby(['Category', 'Store'])['Sales'].sum()
combine_group

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

#### Aggregation

In [1959]:
df2['Sales'].mean()

np.float64(187.5)

In [1960]:
df2['Sales'].sum()

np.int64(1500)

In [1961]:
df2['Sales'].min()

np.int64(100)

In [1962]:
df2['Sales'].max()

np.int64(300)

In [1963]:
df2['Sales'].count()

np.int64(8)

In [1964]:
df2['Sales'].std()

np.float64(66.06274074155351)

In [1965]:
df2['Sales'].median()

np.float64(190.0)

In [1966]:
df2['Sales'].agg(['mean', 'min', 'max', 'sum', 'count', 'std', 'median'])

mean       187.500000
min        100.000000
max        300.000000
sum       1500.000000
count        8.000000
std         66.062741
median     190.000000
Name: Sales, dtype: float64

### Pivot Tables and Crosstabs

#### Pivot tables

In [1967]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df2 = pd.DataFrame(data)

df2['Month'] = df2['Date'].dt.month_name()
df2['Quarter'] = 'Q' + df2['Date'].dt.quarter.astype(str)
df2

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    320     57   John  January      Q1
1  2023-01-02       B   West    895     68   Mary  January      Q1
2  2023-01-03       C  North    480     45    Bob  January      Q1
3  2023-01-04       D  South    864     16  Alice  January      Q1
4  2023-01-05       A   East    215     46   John  January      Q1
5  2023-01-06       B   West    161     43   Mary  January      Q1
6  2023-01-07       C  North    179     72    Bob  January      Q1
7  2023-01-08       D  South    818     62  Alice  January      Q1
8  2023-01-09       A   East    196     80   John  January      Q1
9  2023-01-10       B   West    905     44   Mary  January      Q1
10 2023-01-11       C  North    578     95    Bob  January      Q1
11 2023-01-12       D  South    570     69  Alice  January      Q1
12 2023-01-13       A   East    133     35   John  January      Q1
13 2023-01-14       B   West    363     45   Mary  January      Q1
14 2023-01-15       C  North    715     11    Bob  January      Q1
15 2023-01-16       D  South    488     47  Alice  January      Q1
16 2023-01-17       A   East    679     88   John  January      Q1
17 2023-01-18       B   West    641     21   Mary  January      Q1
18 2023-01-19       C  North    523     34    Bob  January      Q1
19 2023-01-20       D  South    773     18  Alice  January      Q1

In [1968]:
pivot_table_1 = pd.pivot_table(data=df2, values='Sales', index='Region', columns='Product')
pivot_table_1

Product      A      B      C      D
Region
East     308.6    NaN    NaN    NaN
North      NaN    NaN  495.0    NaN
South      NaN    NaN    NaN  702.6
West       NaN  593.0    NaN    NaN

In [1969]:
pivot_table_2 = pd.pivot_table(data=df2, values=['Sales', 'Units'], index='Region', columns='Product')
pivot_table_2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     308.6    NaN    NaN    NaN  61.2   NaN   NaN   NaN
North      NaN    NaN  495.0    NaN   NaN   NaN  51.4   NaN
South      NaN    NaN    NaN  702.6   NaN   NaN   NaN  42.4
West       NaN  593.0    NaN    NaN   NaN  44.2   NaN   NaN

#### Crosstabs

In [1970]:
crosstab_1 = pd.crosstab(df2['Region'], df2['Product'])
crosstab_1

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

### Operations

#### Dataframes basic operations

In [1971]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [1972]:
df2 = df1['A'] + 10
df2

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

#### Applying functions

In [1973]:
def square(x):
    return x**2

In [1974]:
df1['B'].apply(square)

0     100
1     400
2     900
3    1600
4    2500
Name: B, dtype: int64

In [1975]:
df1['D'] = df1['B'].apply(square)
df1

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500

In [1976]:
df1['E'] = df1['A'].apply(lambda x: x**3)
df1

   A   B    C     D    E
0  1  10  100   100    1
1  2  20  200   400    8
2  3  30  300   900   27
3  4  40  400  1600   64
4  5  50  500  2500  125