# Pandas

## Basics

In [8]:
import numpy as np
import pandas as pd

### Series

#### Creation of series

##### Using list

In [9]:
l = [10,20,30]

s = pd.Series(l)
s

0    10
1    20
2    30
dtype: int64

##### Using dictionary

In [10]:
dictionary = {1:10, 2:20, 3:30}

s = pd.Series(dictionary)
s

1    10
2    20
3    30
dtype: int64

##### Using numpy array

In [11]:
arr = np.arange(5)
s = pd.Series(arr)
s

0    0
1    1
2    2
3    3
4    4
dtype: int64

##### index

In [12]:
import string
columns = list(string.ascii_lowercase[:6])

s = pd.Series(np.arange(10,70,10), index=columns)
s

a    10
b    20
c    30
d    40
e    50
f    60
dtype: int64

##### datatype

In [13]:
s2 = pd.Series(np.arange(5), dtype='f4')
s2

0    0.0
1    1.0
2    2.0
3    3.0
4    4.0
dtype: float32

#### Selection and Slicing

##### Selection using iloc

In [14]:
s.iloc[1:4]

b    20
c    30
d    40
dtype: int64

In [15]:
s.iloc[[1, 3, 0]]

b    20
d    40
a    10
dtype: int64

##### Selection using get

In [16]:
# s['g'] will produce an error
print(s.get('g'))

# You can also give it's default value
print(s.get('g', default='Key not found'))

None
Key not found

##### Boolean selection

In [17]:
s[s > 30]

d    40
e    50
f    60
dtype: int64

##### Slicing

In [18]:
slice1 = s[1:4]

slice1

b    20
c    30
d    40
dtype: int64

#### Operations

##### Vectorized Operations

In [19]:
# Every value will be added by 10
s + 10

a    20
b    30
c    40
d    50
e    60
f    70
dtype: int64

##### Useful functions

In [20]:
# Aggregation functions such as sum, min, max, mean, std, median
s.sum()

np.int64(210)

##### Creating numpy array from series

In [21]:
print(s.array, '\n')
print(s.to_numpy())

<NumpyExtensionArray>
[10, 20, 30, 40, 50, 60]
Length: 6, dtype: int64

[10 20 30 40 50 60]

### Dataframes

#### Creation of Dataframes

##### Using Dictionary

In [22]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

##### Using List

In [23]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
print(df2)
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list, columns =columns)
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

##### Use of date_range() and index

In [24]:
dates = pd.date_range("2025-01-20", periods=6)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

                   A         B         C         D
2025-01-20 -1.562878 -1.020161 -1.851090  1.976788
2025-01-21  1.182084 -0.473280 -0.561473  1.338955
2025-01-22 -0.484686  0.181573 -0.502564 -1.293246
2025-01-23  1.042986 -1.381489 -0.153490  0.691791
2025-01-24 -0.292799 -1.103612 -0.855160  1.139972
2025-01-25  0.424183  0.971906 -0.260780 -1.188043

#### Viewing Data

##### Header and Footer of Dataframe

In [25]:
print(df.head(), '\n')
print(df.tail(3))

                   A         B         C         D
2025-01-20 -1.562878 -1.020161 -1.851090  1.976788
2025-01-21  1.182084 -0.473280 -0.561473  1.338955
2025-01-22 -0.484686  0.181573 -0.502564 -1.293246
2025-01-23  1.042986 -1.381489 -0.153490  0.691791
2025-01-24 -0.292799 -1.103612 -0.855160  1.139972

                   A         B        C         D
2025-01-23  1.042986 -1.381489 -0.15349  0.691791
2025-01-24 -0.292799 -1.103612 -0.85516  1.139972
2025-01-25  0.424183  0.971906 -0.26078 -1.188043

##### Information about Dataframe

In [26]:
print(df.index, '\n')
print(df.columns, '\n')
print(df.dtypes)

DatetimeIndex(['2025-01-20', '2025-01-21', '2025-01-22', '2025-01-23',
               '2025-01-24', '2025-01-25'],
              dtype='datetime64[us]', freq='D')

Index(['A', 'B', 'C', 'D'], dtype='str')

A    float64
B    float64
C    float64
D    float64
dtype: object

In [27]:
print(df.info(), '\n')
print(df.describe())

<class 'pandas.DataFrame'>
DatetimeIndex: 6 entries, 2025-01-20 to 2025-01-25
Freq: D
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       6 non-null      float64
 1   B       6 non-null      float64
 2   C       6 non-null      float64
 3   D       6 non-null      float64
dtypes: float64(4)
memory usage: 240.0 bytes
None

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.051482 -0.470844 -0.697426  0.444370
std    1.040424  0.898732  0.616247  1.369507
min   -1.562878 -1.381489 -1.851090 -1.293246
25%   -0.436715 -1.082750 -0.781738 -0.718084
50%    0.065692 -0.746721 -0.532018  0.915882
75%    0.888285  0.017860 -0.321226  1.289210
max    1.182084  0.971906 -0.153490  1.976788

##### Transformation of Dataframe

In [28]:
print(df.T, '\n')
print(df.to_numpy())

   2025-01-20  2025-01-21  2025-01-22  2025-01-23  2025-01-24  2025-01-25
A   -1.562878    1.182084   -0.484686    1.042986   -0.292799    0.424183
B   -1.020161   -0.473280    0.181573   -1.381489   -1.103612    0.971906
C   -1.851090   -0.561473   -0.502564   -0.153490   -0.855160   -0.260780
D    1.976788    1.338955   -1.293246    0.691791    1.139972   -1.188043

[[-1.56287817 -1.02016094 -1.85109037  1.97678786]
 [ 1.18208413 -0.47328036 -0.5614726   1.33895547]
 [-0.48468642  0.18157324 -0.5025641  -1.29324578]
 [ 1.04298608 -1.38148877 -0.15349047  0.69179144]
 [-0.29279924 -1.10361238 -0.85516039  1.13997176]
 [ 0.424183    0.97190596 -0.26077956 -1.18804284]]

##### Sorting in Dataframe

In [29]:
df.sort_index(axis=1, ascending=False)

                   D         C         B         A
2025-01-20  1.976788 -1.851090 -1.020161 -1.562878
2025-01-21  1.338955 -0.561473 -0.473280  1.182084
2025-01-22 -1.293246 -0.502564  0.181573 -0.484686
2025-01-23  0.691791 -0.153490 -1.381489  1.042986
2025-01-24  1.139972 -0.855160 -1.103612 -0.292799
2025-01-25 -1.188043 -0.260780  0.971906  0.424183

In [30]:
df.sort_values(by="B")

                   A         B         C         D
2025-01-23  1.042986 -1.381489 -0.153490  0.691791
2025-01-24 -0.292799 -1.103612 -0.855160  1.139972
2025-01-20 -1.562878 -1.020161 -1.851090  1.976788
2025-01-21  1.182084 -0.473280 -0.561473  1.338955
2025-01-22 -0.484686  0.181573 -0.502564 -1.293246
2025-01-25  0.424183  0.971906 -0.260780 -1.188043

### Selection

##### Getitem ([])

In [31]:
# Column
df['A']

2025-01-20   -1.562878
2025-01-21    1.182084
2025-01-22   -0.484686
2025-01-23    1.042986
2025-01-24   -0.292799
2025-01-25    0.424183
Freq: D, Name: A, dtype: float64

In [32]:
# Multiple columns
df[['A', 'B']]

                   A         B
2025-01-20 -1.562878 -1.020161
2025-01-21  1.182084 -0.473280
2025-01-22 -0.484686  0.181573
2025-01-23  1.042986 -1.381489
2025-01-24 -0.292799 -1.103612
2025-01-25  0.424183  0.971906

In [33]:
# rows
df[0:3]

                   A         B         C         D
2025-01-20 -1.562878 -1.020161 -1.851090  1.976788
2025-01-21  1.182084 -0.473280 -0.561473  1.338955
2025-01-22 -0.484686  0.181573 -0.502564 -1.293246

##### Selection by label

In [34]:
# row
df.loc[dates[0]]

A   -1.562878
B   -1.020161
C   -1.851090
D    1.976788
Name: 2025-01-20 00:00:00, dtype: float64

In [35]:
# all rows with only 'A' and 'B' column
df.loc[:, ['A', 'B']]

                   A         B
2025-01-20 -1.562878 -1.020161
2025-01-21  1.182084 -0.473280
2025-01-22 -0.484686  0.181573
2025-01-23  1.042986 -1.381489
2025-01-24 -0.292799 -1.103612
2025-01-25  0.424183  0.971906

In [36]:
# subset of selected rows and columns
df.loc['2025-01-22':'2025-01-25', ['A', 'B']]

                   A         B
2025-01-22 -0.484686  0.181573
2025-01-23  1.042986 -1.381489
2025-01-24 -0.292799 -1.103612
2025-01-25  0.424183  0.971906

In [37]:
# Single element
print(df.loc[dates[0], 'A'])
print(df.at[dates[0], 'A'])

-1.5628781722226412
-1.5628781722226412

##### Selection by position

In [38]:
# row
df.iloc[2]

A   -0.484686
B    0.181573
C   -0.502564
D   -1.293246
Name: 2025-01-22 00:00:00, dtype: float64

In [39]:
# subset
df.iloc[1:3, :2]

                   A         B
2025-01-21  1.182084 -0.473280
2025-01-22 -0.484686  0.181573

In [40]:
# list of integer position locations
df.iloc[[1, 2, 4], [1, 3]]

                   B         D
2025-01-21 -0.473280  1.338955
2025-01-22  0.181573 -1.293246
2025-01-24 -1.103612  1.139972

In [41]:
# Single element
print(df.iloc[1, 2])
print(df.iat[1, 2])

-0.5614725961706885
-0.5614725961706885

##### Boolean indexing

In [42]:
#Select rows where df.A is greater than 0.
df[df['A'] > 0]

                   A         B         C         D
2025-01-21  1.182084 -0.473280 -0.561473  1.338955
2025-01-23  1.042986 -1.381489 -0.153490  0.691791
2025-01-25  0.424183  0.971906 -0.260780 -1.188043

In [43]:
#Selecting values from a DataFrame where a boolean condition is met:
df[df > 0]

                   A         B   C         D
2025-01-20       NaN       NaN NaN  1.976788
2025-01-21  1.182084       NaN NaN  1.338955
2025-01-22       NaN  0.181573 NaN       NaN
2025-01-23  1.042986       NaN NaN  0.691791
2025-01-24       NaN       NaN NaN  1.139972
2025-01-25  0.424183  0.971906 NaN       NaN

### Setting

##### Setting new column

In [44]:
s1 = pd.Series([1,2,3,4,5,6], index=pd.date_range('2025-01-20', periods=6))
df['F'] = s1
df.head(3)

                   A         B         C         D  F
2025-01-20 -1.562878 -1.020161 -1.851090  1.976788  1
2025-01-21  1.182084 -0.473280 -0.561473  1.338955  2
2025-01-22 -0.484686  0.181573 -0.502564 -1.293246  3

##### Modifying column

In [45]:
df['D'] = np.array([5] * len(df))
df.head(3)

                   A         B         C  D  F
2025-01-20 -1.562878 -1.020161 -1.851090  5  1
2025-01-21  1.182084 -0.473280 -0.561473  5  2
2025-01-22 -0.484686  0.181573 -0.502564  5  3

##### Setting new element

In [46]:
df.at[dates[0], 'A'] = 0
df.iat[0, 1] = 0
df.iloc[0]

A    0.00000
B    0.00000
C   -1.85109
D    5.00000
F    1.00000
Name: 2025-01-20 00:00:00, dtype: float64

##### Setting new row

In [47]:
df.loc[pd.Timestamp('2025-01-29')] = np.append(np.random.randn(3), [5, 7])
df.tail(3)
# You can modify row like this also.

                   A         B         C    D    F
2025-01-24 -0.292799 -1.103612 -0.855160  5.0  5.0
2025-01-25  0.424183  0.971906 -0.260780  5.0  6.0
2025-01-29 -0.049738 -1.295281  1.178504  5.0  7.0

##### Modifying the index of row

In [48]:
df.rename(index={pd.Timestamp('2025-01-29'): pd.Timestamp('2025-01-26')}, inplace=True)
df.tail(3)

                   A         B         C    D    F
2025-01-24 -0.292799 -1.103612 -0.855160  5.0  5.0
2025-01-25  0.424183  0.971906 -0.260780  5.0  6.0
2025-01-26 -0.049738 -1.295281  1.178504  5.0  7.0

##### Removing column

In [49]:
df.drop('A', axis=1).head(3)

# df.drop('A', axis=1, inplace=True) will delete it permanently from memory.

                   B         C    D    F
2025-01-20  0.000000 -1.851090  5.0  1.0
2025-01-21 -0.473280 -0.561473  5.0  2.0
2025-01-22  0.181573 -0.502564  5.0  3.0

##### Removing row

In [50]:
df.drop('2025-01-24')

                   A         B         C    D    F
2025-01-20  0.000000  0.000000 -1.851090  5.0  1.0
2025-01-21  1.182084 -0.473280 -0.561473  5.0  2.0
2025-01-22 -0.484686  0.181573 -0.502564  5.0  3.0
2025-01-23  1.042986 -1.381489 -0.153490  5.0  4.0
2025-01-25  0.424183  0.971906 -0.260780  5.0  6.0
2025-01-26 -0.049738 -1.295281  1.178504  5.0  7.0

### Missing Data

#### Finding missing data

In [51]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df2 = pd.DataFrame(data)
df2

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [52]:
df2.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [53]:
df2.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [54]:
df2.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

#### Removing missing data

In [55]:
df2.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [56]:
df2.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

#### Filling missing data

In [57]:
df2.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [58]:
values = {'A':0,'B':100,"C":300,'D':400}
df2.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

### Merge and Grouping

#### Merging

In [59]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [60]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [61]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [62]:
pd.merge(employees, salaries)             # pd.merge(employees, salaries, on='employee_id', how='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [63]:
pd.merge(employees, salaries, on='employee_id', how='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [64]:
pd.merge(employees, salaries, on='employee_id', how='left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [65]:
pd.merge(employees, salaries, on='employee_id', how='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

#### Concating

In [66]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [67]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [68]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [69]:
pd.concat([df1, df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [70]:
pd.concat([df1, df2], axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

#### Joining

In [71]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

print(df1, df2, sep='\n\n')

      name
1    Alice
2      Bob
3  Charlie

   score
2     85
3     90
4     75

In [72]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [73]:
df1.join(df2, how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

#### Grouping

In [74]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df2 = pd.DataFrame(data)
df2

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [75]:
cat_group = df2.groupby('Category')
cat_group

In [76]:
cat_group = df2.groupby('Category')['Sales'].sum()
cat_group

Category
A    570
B    930
Name: Sales, dtype: int64

In [77]:
store_group = df2.groupby('Store')['Sales'].sum()
store_group

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [78]:
combine_group = df2.groupby(['Category', 'Store'])['Sales'].sum()
combine_group

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

### Stack and Pivot Tables

#### Stack & Unstack

In [79]:
arrays = [
   ["bar", "bar", "baz", "baz"],
   ["one", "two", "one", "two"],
]

index = pd.MultiIndex.from_arrays(arrays, names=["first", "second"])
df = pd.DataFrame(np.random.randn(4, 2), index=index, columns=["A", "B"])
print(df, '\n')

stacked = df.stack()
print(stacked)

                     A         B
first second
bar   one    -0.311310  0.462777
      two    -0.004295 -1.657096
baz   one     0.011694 -0.059713
      two     1.272130  0.174064

first  second
bar    one     A   -0.311310
               B    0.462777
       two     A   -0.004295
               B   -1.657096
baz    one     A    0.011694
               B   -0.059713
       two     A    1.272130
               B    0.174064
dtype: float64

In [80]:
unstacked = stacked.unstack()
print(unstacked, '\n')

unstacked = stacked.unstack(0)
print(unstacked, '\n')

unstacked = stacked.unstack(1)
print(unstacked)

                     A         B
first second
bar   one    -0.311310  0.462777
      two    -0.004295 -1.657096
baz   one     0.011694 -0.059713
      two     1.272130  0.174064

first          bar       baz
second
one    A -0.311310  0.011694
       B  0.462777 -0.059713
two    A -0.004295  1.272130
       B -1.657096  0.174064

second        one       two
first
bar   A -0.311310 -0.004295
      B  0.462777 -1.657096
baz   A  0.011694  1.272130
      B -0.059713  0.174064

#### Pivot tables

In [81]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df2 = pd.DataFrame(data)

df2['Month'] = df2['Date'].dt.month_name()
df2['Quarter'] = 'Q' + df2['Date'].dt.quarter.astype(str)
df2

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    298     42   John  January      Q1
1  2023-01-02       B   West    108     15   Mary  January      Q1
2  2023-01-03       C  North    504     86    Bob  January      Q1
3  2023-01-04       D  South    827     65  Alice  January      Q1
4  2023-01-05       A   East    369     83   John  January      Q1
5  2023-01-06       B   West    286     33   Mary  January      Q1
6  2023-01-07       C  North    144     36    Bob  January      Q1
7  2023-01-08       D  South    757     20  Alice  January      Q1
8  2023-01-09       A   East    701     37   John  January      Q1
9  2023-01-10       B   West    835     64   Mary  January      Q1
10 2023-01-11       C  North    630     39    Bob  January      Q1
11 2023-01-12       D  South    711     72  Alice  January      Q1
12 2023-01-13       A   East    936     34   John  January      Q1
13 2023-01-14       B   West    916     73   Mary  January      Q1
14 2023-01-15       C  North    526     49    Bob  January      Q1
15 2023-01-16       D  South    751     16  Alice  January      Q1
16 2023-01-17       A   East    162     70   John  January      Q1
17 2023-01-18       B   West    448     56   Mary  January      Q1
18 2023-01-19       C  North    468     98    Bob  January      Q1
19 2023-01-20       D  South    238     44  Alice  January      Q1

In [82]:
pivot_table_1 = pd.pivot_table(data=df2, values='Sales', index='Region', columns='Product')
pivot_table_1

Product      A      B      C      D
Region
East     493.2    NaN    NaN    NaN
North      NaN    NaN  454.4    NaN
South      NaN    NaN    NaN  656.8
West       NaN  518.6    NaN    NaN

In [83]:
pivot_table_2 = pd.pivot_table(data=df2, values=['Sales', 'Units'], index='Region', columns='Product')
pivot_table_2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     493.2    NaN    NaN    NaN  53.2   NaN   NaN   NaN
North      NaN    NaN  454.4    NaN   NaN   NaN  61.6   NaN
South      NaN    NaN    NaN  656.8   NaN   NaN   NaN  43.4
West       NaN  518.6    NaN    NaN   NaN  48.2   NaN   NaN

#### Crosstabs

In [84]:
crosstab_1 = pd.crosstab(df2['Region'], df2['Product'])
crosstab_1

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

### Operations

#### Dataframes basic operations

##### Aggregation functions

In [85]:
df1 = pd.DataFrame({
    'Id': [1, 2, 3, 4, 5],
    'Price': [600, 720, 590, 650, 700],
    'Sales': [1000, 1000, 1200, 900, 1000]
})
df1

   Id  Price  Sales
0   1    600   1000
1   2    720   1000
2   3    590   1200
3   4    650    900
4   5    700   1000

In [86]:
print('Mean : ', df1['Sales'].mean())
print('Sum : ', df1['Sales'].sum())
print('Min : ', df1['Sales'].min())
print('Max : ', df1['Sales'].max())
print('Count : ', df1['Sales'].count())
print('Std : ', df1['Sales'].std())
print('Median : ', df1['Sales'].median())

Mean :  1020.0
Sum :  5100
Min :  900
Max :  1200
Count :  5
Std :  109.54451150103323
Median :  1000.0

In [87]:
df1['Sales'].agg(['mean', 'min', 'max', 'sum', 'count', 'std', 'median'])

mean      1020.000000
min        900.000000
max       1200.000000
sum       5100.000000
count        5.000000
std        109.544512
median    1000.000000
Name: Sales, dtype: float64

##### mode function

In [88]:
# mode function returns the most frequently occured values in a series or a dataframe.
s = pd.Series(np.array([1, 2, 3, 2, 2, 1]), index=list('abcdef'))
s.mode()

s2 = pd.Series(np.array([1, 3, 3, 1, 2, 4]), index=list('abcdef'))
s2.mode()

0    1
1    3
dtype: int64

##### Vectorized Operations

In [89]:
# Every value will be multiplied by 10
df1 * 10

   Id  Price  Sales
0  10   6000  10000
1  20   7200  10000
2  30   5900  12000
3  40   6500   9000
4  50   7000  10000

#### Applying functions

In [90]:
def square(x):
    return x**2

In [91]:
df1['Id'].apply(square)

0     1
1     4
2     9
3    16
4    25
Name: Id, dtype: int64

In [92]:
df1['raw Id'] = df1['Id'].apply(lambda x: x**3)
df1

   Id  Price  Sales  raw Id
0   1    600   1000       1
1   2    720   1000       8
2   3    590   1200      27
3   4    650    900      64
4   5    700   1000     125