# Pandas

## Basics

In [1]:
import numpy as np
import pandas as pd

### Series

#### Creation of series

##### Using list

In [4]:
l = [10,20,30]

s = pd.Series(l)
s

0    10
1    20
2    30
dtype: int64

##### Using dictionary

In [5]:
dictionary = {1:10, 2:20, 3:30}

s = pd.Series(dictionary)
s

1    10
2    20
3    30
dtype: int64

##### Using numpy array

In [6]:
arr = np.arange(5)
s = pd.Series(arr)
s

0    0
1    1
2    2
3    3
4    4
dtype: int64

##### index

In [7]:
import string
columns = list(string.ascii_lowercase[:6])

s = pd.Series(np.arange(10,70,10), index=columns)
s

a    10
b    20
c    30
d    40
e    50
f    60
dtype: int64

##### datatype

In [8]:
s2 = pd.Series(np.arange(5), dtype='f4')
s2

0    0.0
1    1.0
2    2.0
3    3.0
4    4.0
dtype: float32

#### Selection and Slicing

##### Selection using iloc

In [9]:
s.iloc[1:4]

b    20
c    30
d    40
dtype: int64

In [10]:
s.iloc[[1, 3, 0]]

b    20
d    40
a    10
dtype: int64

##### Selection using get

In [11]:
# s['g'] will produce an error
print(s.get('g'))

# You can also give it's default value
print(s.get('g', default='Key not found'))

None
Key not found

##### Boolean selection

In [12]:
s[s > 30]

d    40
e    50
f    60
dtype: int64

##### Slicing

In [13]:
slice1 = s[1:4]

slice1

b    20
c    30
d    40
dtype: int64

#### Operations

##### Vectorized Operations

In [14]:
# Every value will be added by 10
s + 10

a    20
b    30
c    40
d    50
e    60
f    70
dtype: int64

##### Useful functions

In [15]:
# Aggregation functions such as sum, min, max, mean, std, median
s.sum()

np.int64(210)

##### Creating numpy array from series

In [16]:
print(s.array, '\n')
print(s.to_numpy())

<NumpyExtensionArray>
[10, 20, 30, 40, 50, 60]
Length: 6, dtype: int64

[10 20 30 40 50 60]

### Dataframes

#### Creation of Dataframes

##### Using Dictionary

In [17]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

##### Using List

In [18]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
print(df2)
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list, columns =columns)
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

##### Use of date_range() and index

In [19]:
dates = pd.date_range("2025-01-20", periods=6)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

                   A         B         C         D
2025-01-20 -0.545678 -0.427257 -1.292691  0.748727
2025-01-21  0.687145  0.184030  0.585852 -0.533815
2025-01-22  0.818708 -0.090662  0.538791  0.070809
2025-01-23  1.804694  0.135559 -0.007469 -0.951179
2025-01-24 -0.126337 -0.293950 -0.712291  0.517237
2025-01-25 -0.697757  0.775963  0.011384  1.002143

#### Viewing Data

##### Header and Footer of Dataframe

In [20]:
print(df.head(), '\n')
print(df.tail(3))

                   A         B         C         D
2025-01-20 -0.545678 -0.427257 -1.292691  0.748727
2025-01-21  0.687145  0.184030  0.585852 -0.533815
2025-01-22  0.818708 -0.090662  0.538791  0.070809
2025-01-23  1.804694  0.135559 -0.007469 -0.951179
2025-01-24 -0.126337 -0.293950 -0.712291  0.517237

                   A         B         C         D
2025-01-23  1.804694  0.135559 -0.007469 -0.951179
2025-01-24 -0.126337 -0.293950 -0.712291  0.517237
2025-01-25 -0.697757  0.775963  0.011384  1.002143

##### Information about Dataframe

In [21]:
print(df.index, '\n')
print(df.columns, '\n')
print(df.dtypes)

DatetimeIndex(['2025-01-20', '2025-01-21', '2025-01-22', '2025-01-23',
               '2025-01-24', '2025-01-25'],
              dtype='datetime64[us]', freq='D')

Index(['A', 'B', 'C', 'D'], dtype='str')

A    float64
B    float64
C    float64
D    float64
dtype: object

In [22]:
print(df.info(), '\n')
print(df.describe())

<class 'pandas.DataFrame'>
DatetimeIndex: 6 entries, 2025-01-20 to 2025-01-25
Freq: D
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       6 non-null      float64
 1   B       6 non-null      float64
 2   C       6 non-null      float64
 3   D       6 non-null      float64
dtypes: float64(4)
memory usage: 240.0 bytes
None

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.323463  0.047280 -0.146071  0.142320
std    0.956263  0.428515  0.732679  0.762312
min   -0.697757 -0.427257 -1.292691 -0.951179
25%   -0.440843 -0.243128 -0.536085 -0.382659
50%    0.280404  0.022448  0.001957  0.294023
75%    0.785817  0.171912  0.406939  0.690855
max    1.804694  0.775963  0.585852  1.002143

##### Transformation of Dataframe

In [23]:
print(df.T, '\n')
print(df.to_numpy())

   2025-01-20  2025-01-21  2025-01-22  2025-01-23  2025-01-24  2025-01-25
A   -0.545678    0.687145    0.818708    1.804694   -0.126337   -0.697757
B   -0.427257    0.184030   -0.090662    0.135559   -0.293950    0.775963
C   -1.292691    0.585852    0.538791   -0.007469   -0.712291    0.011384
D    0.748727   -0.533815    0.070809   -0.951179    0.517237    1.002143

[[-0.54567758 -0.4272572  -1.29269128  0.74872748]
 [ 0.68714464  0.1840297   0.58585248 -0.53381485]
 [ 0.81870834 -0.09066194  0.5387908   0.07080851]
 [ 1.80469433  0.13555881 -0.00746935 -0.95117907]
 [-0.12633736 -0.29395018 -0.71229061  0.51723689]
 [-0.69775691  0.77596317  0.01138414  1.00214268]]

##### Sorting in Dataframe

In [24]:
df.sort_index(axis=1, ascending=False)

                   D         C         B         A
2025-01-20  0.748727 -1.292691 -0.427257 -0.545678
2025-01-21 -0.533815  0.585852  0.184030  0.687145
2025-01-22  0.070809  0.538791 -0.090662  0.818708
2025-01-23 -0.951179 -0.007469  0.135559  1.804694
2025-01-24  0.517237 -0.712291 -0.293950 -0.126337
2025-01-25  1.002143  0.011384  0.775963 -0.697757

In [25]:
df.sort_values(by="B")

                   A         B         C         D
2025-01-20 -0.545678 -0.427257 -1.292691  0.748727
2025-01-24 -0.126337 -0.293950 -0.712291  0.517237
2025-01-22  0.818708 -0.090662  0.538791  0.070809
2025-01-23  1.804694  0.135559 -0.007469 -0.951179
2025-01-21  0.687145  0.184030  0.585852 -0.533815
2025-01-25 -0.697757  0.775963  0.011384  1.002143

### Selection

##### Getitem ([])

In [26]:
# Column
df['A']

2025-01-20   -0.545678
2025-01-21    0.687145
2025-01-22    0.818708
2025-01-23    1.804694
2025-01-24   -0.126337
2025-01-25   -0.697757
Freq: D, Name: A, dtype: float64

In [27]:
# Multiple columns
df[['A', 'B']]

                   A         B
2025-01-20 -0.545678 -0.427257
2025-01-21  0.687145  0.184030
2025-01-22  0.818708 -0.090662
2025-01-23  1.804694  0.135559
2025-01-24 -0.126337 -0.293950
2025-01-25 -0.697757  0.775963

In [28]:
# rows
df[0:3]

                   A         B         C         D
2025-01-20 -0.545678 -0.427257 -1.292691  0.748727
2025-01-21  0.687145  0.184030  0.585852 -0.533815
2025-01-22  0.818708 -0.090662  0.538791  0.070809

##### Selection by label

In [29]:
# row
df.loc[dates[0]]

A   -0.545678
B   -0.427257
C   -1.292691
D    0.748727
Name: 2025-01-20 00:00:00, dtype: float64

In [30]:
# all rows with only 'A' and 'B' column
df.loc[:, ['A', 'B']]

                   A         B
2025-01-20 -0.545678 -0.427257
2025-01-21  0.687145  0.184030
2025-01-22  0.818708 -0.090662
2025-01-23  1.804694  0.135559
2025-01-24 -0.126337 -0.293950
2025-01-25 -0.697757  0.775963

In [31]:
# subset of selected rows and columns
df.loc['2025-01-22':'2025-01-25', ['A', 'B']]

                   A         B
2025-01-22  0.818708 -0.090662
2025-01-23  1.804694  0.135559
2025-01-24 -0.126337 -0.293950
2025-01-25 -0.697757  0.775963

In [32]:
# Single element
print(df.loc[dates[0], 'A'])
print(df.at[dates[0], 'A'])

-0.5456775758094473
-0.5456775758094473

##### Selection by position

In [33]:
# row
df.iloc[2]

A    0.818708
B   -0.090662
C    0.538791
D    0.070809
Name: 2025-01-22 00:00:00, dtype: float64

In [34]:
# subset
df.iloc[1:3, :2]

                   A         B
2025-01-21  0.687145  0.184030
2025-01-22  0.818708 -0.090662

In [35]:
# list of integer position locations
df.iloc[[1, 2, 4], [1, 3]]

                   B         D
2025-01-21  0.184030 -0.533815
2025-01-22 -0.090662  0.070809
2025-01-24 -0.293950  0.517237

In [36]:
# Single element
print(df.iloc[1, 2])
print(df.iat[1, 2])

0.5858524821428962
0.5858524821428962

##### Boolean indexing

In [37]:
#Select rows where df.A is greater than 0.
df[df['A'] > 0]

                   A         B         C         D
2025-01-21  0.687145  0.184030  0.585852 -0.533815
2025-01-22  0.818708 -0.090662  0.538791  0.070809
2025-01-23  1.804694  0.135559 -0.007469 -0.951179

In [38]:
#Selecting values from a DataFrame where a boolean condition is met:
df[df > 0]

                   A         B         C         D
2025-01-20       NaN       NaN       NaN  0.748727
2025-01-21  0.687145  0.184030  0.585852       NaN
2025-01-22  0.818708       NaN  0.538791  0.070809
2025-01-23  1.804694  0.135559       NaN       NaN
2025-01-24       NaN       NaN       NaN  0.517237
2025-01-25       NaN  0.775963  0.011384  1.002143

### Setting

##### Setting new column

In [39]:
s1 = pd.Series([1,2,3,4,5,6], index=pd.date_range('2025-01-20', periods=6))
df['F'] = s1
df.head(3)

                   A         B         C         D  F
2025-01-20 -0.545678 -0.427257 -1.292691  0.748727  1
2025-01-21  0.687145  0.184030  0.585852 -0.533815  2
2025-01-22  0.818708 -0.090662  0.538791  0.070809  3

##### Modifying column

In [40]:
df['D'] = np.array([5] * len(df))
df.head(3)

                   A         B         C  D  F
2025-01-20 -0.545678 -0.427257 -1.292691  5  1
2025-01-21  0.687145  0.184030  0.585852  5  2
2025-01-22  0.818708 -0.090662  0.538791  5  3

##### Setting new element

In [41]:
df.at[dates[0], 'A'] = 0
df.iat[0, 1] = 0
df.iloc[0]

A    0.000000
B    0.000000
C   -1.292691
D    5.000000
F    1.000000
Name: 2025-01-20 00:00:00, dtype: float64

##### Setting new row

In [42]:
df.loc[pd.Timestamp('2025-01-29')] = np.append(np.random.randn(3), [5, 7])
df.tail(3)
# You can modify row like this also.

                   A         B         C    D    F
2025-01-24 -0.126337 -0.293950 -0.712291  5.0  5.0
2025-01-25 -0.697757  0.775963  0.011384  5.0  6.0
2025-01-29 -1.151677  1.011460 -0.379170  5.0  7.0

##### Modifying the index of row

In [43]:
df.rename(index={pd.Timestamp('2025-01-29'): pd.Timestamp('2025-01-26')}, inplace=True)
df.tail(3)

                   A         B         C    D    F
2025-01-24 -0.126337 -0.293950 -0.712291  5.0  5.0
2025-01-25 -0.697757  0.775963  0.011384  5.0  6.0
2025-01-26 -1.151677  1.011460 -0.379170  5.0  7.0

##### Removing column

In [44]:
df.drop('A', axis=1).head(3)

# df.drop('A', axis=1, inplace=True) will delete it permanently from memory.

                   B         C    D    F
2025-01-20  0.000000 -1.292691  5.0  1.0
2025-01-21  0.184030  0.585852  5.0  2.0
2025-01-22 -0.090662  0.538791  5.0  3.0

##### Removing row

In [45]:
df.drop('2025-01-24')

                   A         B         C    D    F
2025-01-20  0.000000  0.000000 -1.292691  5.0  1.0
2025-01-21  0.687145  0.184030  0.585852  5.0  2.0
2025-01-22  0.818708 -0.090662  0.538791  5.0  3.0
2025-01-23  1.804694  0.135559 -0.007469  5.0  4.0
2025-01-25 -0.697757  0.775963  0.011384  5.0  6.0
2025-01-26 -1.151677  1.011460 -0.379170  5.0  7.0

### Missing Data

#### Finding missing data

In [2]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df2 = pd.DataFrame(data)
df2

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [47]:
df2.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [48]:
df2.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [49]:
df2.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

#### Removing missing data

In [50]:
df2.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [51]:
df2.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

#### Filling missing data

##### By given values

In [3]:
df2.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [4]:
values = {'A':0,'B':100,"C":300,'D':400}
df2.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

##### By combine_first()

In [8]:
df3 = pd.DataFrame(np.arange(-1,-31,-1).reshape(6,5), columns=list('ABCDE'))

# combine_first() will use second dataframe's values to fill nan values of first dataframe.
df2.combine_first(df3)

# Important about combine_first() :
# combine_first() aligns both DataFrames by their index and columns.
# It can also include labels and columns that exist only in one DataFrame.

      A   B     C     D   E
0   1.0   1   1.0   1.0  -5
1   2.0   2   2.0  -9.0 -10
2 -11.0   3   3.0 -14.0 -15
3   4.0   4 -18.0 -19.0 -20
4   5.0   5 -23.0   5.0 -25
5 -26.0 -27 -28.0 -29.0 -30

##### By combine()

In [12]:
# combine() can combine values as defined.
temp_df1 = pd.DataFrame(np.array(np.random.randint(1,11,12)).reshape(4,3), columns=list('ABC'))
temp_df2 = pd.DataFrame(np.array(np.random.randint(1,11,12)).reshape(4,3), columns=list('ABC'))
print(temp_df1, '\n', temp_df2, '\n')

# Using in-built function
print(temp_df1.combine(temp_df2, max))

# Using custom(UDF / lambda function) function
def temp_func(x, y):
    if(x > y):
        return x + y
    else:
        return x - y
    
print(temp_df1.combine(temp_df2, temp_func))

    A  B  C
0   8  3  7
1   1  8  2
2  10  2  9
3   3  6  1
     A  B  C
0   9  7  5
1   6  7  3
2  10  7  5
3   3  5  3

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

### Merge and Grouping

#### Merging

In [55]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [56]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [57]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [58]:
pd.merge(employees, salaries)             # pd.merge(employees, salaries, on='employee_id', how='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [59]:
pd.merge(employees, salaries, on='employee_id', how='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [60]:
pd.merge(employees, salaries, on='employee_id', how='left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [61]:
pd.merge(employees, salaries, on='employee_id', how='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

#### Concating

In [62]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [63]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [64]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [65]:
pd.concat([df1, df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [66]:
pd.concat([df1, df2], axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

#### Joining

In [67]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

print(df1, df2, sep='\n\n')

      name
1    Alice
2      Bob
3  Charlie

   score
2     85
3     90
4     75

In [68]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [69]:
df1.join(df2, how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

#### Grouping

In [70]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df2 = pd.DataFrame(data)
df2

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [71]:
cat_group = df2.groupby('Category')
cat_group

In [72]:
cat_group = df2.groupby('Category')['Sales'].sum()
cat_group

Category
A    570
B    930
Name: Sales, dtype: int64

In [73]:
store_group = df2.groupby('Store')['Sales'].sum()
store_group

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [74]:
combine_group = df2.groupby(['Category', 'Store'])['Sales'].sum()
combine_group

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

### Stack and Pivot Tables

#### Stack & Unstack

In [75]:
arrays = [
   ["bar", "bar", "baz", "baz"],
   ["one", "two", "one", "two"],
]

index = pd.MultiIndex.from_arrays(arrays, names=["first", "second"])
df = pd.DataFrame(np.random.randn(4, 2), index=index, columns=["A", "B"])
print(df, '\n')

stacked = df.stack()
print(stacked)

                     A         B
first second
bar   one    -0.041413  1.164425
      two    -1.105338  2.233026
baz   one    -1.152058  1.152668
      two    -1.811472 -0.560159

first  second
bar    one     A   -0.041413
               B    1.164425
       two     A   -1.105338
               B    2.233026
baz    one     A   -1.152058
               B    1.152668
       two     A   -1.811472
               B   -0.560159
dtype: float64

In [76]:
unstacked = stacked.unstack()
print(unstacked, '\n')

unstacked = stacked.unstack(0)
print(unstacked, '\n')

unstacked = stacked.unstack(1)
print(unstacked)

                     A         B
first second
bar   one    -0.041413  1.164425
      two    -1.105338  2.233026
baz   one    -1.152058  1.152668
      two    -1.811472 -0.560159

first          bar       baz
second
one    A -0.041413 -1.152058
       B  1.164425  1.152668
two    A -1.105338 -1.811472
       B  2.233026 -0.560159

second        one       two
first
bar   A -0.041413 -1.105338
      B  1.164425  2.233026
baz   A -1.152058 -1.811472
      B  1.152668 -0.560159

#### Pivot tables

In [77]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df2 = pd.DataFrame(data)

df2['Month'] = df2['Date'].dt.month_name()
df2['Quarter'] = 'Q' + df2['Date'].dt.quarter.astype(str)
df2

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    258     74   John  January      Q1
1  2023-01-02       B   West    444     72   Mary  January      Q1
2  2023-01-03       C  North    450     34    Bob  January      Q1
3  2023-01-04       D  South    805     86  Alice  January      Q1
4  2023-01-05       A   East    167     97   John  January      Q1
5  2023-01-06       B   West    406     60   Mary  January      Q1
6  2023-01-07       C  North    116     68    Bob  January      Q1
7  2023-01-08       D  South    921     82  Alice  January      Q1
8  2023-01-09       A   East    756     59   John  January      Q1
9  2023-01-10       B   West    896     12   Mary  January      Q1
10 2023-01-11       C  North    921     21    Bob  January      Q1
11 2023-01-12       D  South    595     16  Alice  January      Q1
12 2023-01-13       A   East    896     23   John  January      Q1
13 2023-01-14       B   West    444     76   Mary  January      Q1
14 2023-01-15       C  North    653     39    Bob  January      Q1
15 2023-01-16       D  South    479     69  Alice  January      Q1
16 2023-01-17       A   East    121     37   John  January      Q1
17 2023-01-18       B   West    757     46   Mary  January      Q1
18 2023-01-19       C  North    990     54    Bob  January      Q1
19 2023-01-20       D  South    300     99  Alice  January      Q1

In [78]:
pivot_table_1 = pd.pivot_table(data=df2, values='Sales', index='Region', columns='Product')
pivot_table_1

Product      A      B      C      D
Region
East     439.6    NaN    NaN    NaN
North      NaN    NaN  626.0    NaN
South      NaN    NaN    NaN  620.0
West       NaN  589.4    NaN    NaN

In [79]:
pivot_table_2 = pd.pivot_table(data=df2, values=['Sales', 'Units'], index='Region', columns='Product')
pivot_table_2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     439.6    NaN    NaN    NaN  58.0   NaN   NaN   NaN
North      NaN    NaN  626.0    NaN   NaN   NaN  43.2   NaN
South      NaN    NaN    NaN  620.0   NaN   NaN   NaN  70.4
West       NaN  589.4    NaN    NaN   NaN  53.2   NaN   NaN

#### Crosstabs

In [80]:
crosstab_1 = pd.crosstab(df2['Region'], df2['Product'])
crosstab_1

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

### Operations

#### Dataframes basic operations

##### Aggregation functions

In [81]:
df1 = pd.DataFrame({
    'Id': [1, 2, 3, 4, 5],
    'Price': [600, 720, 590, 650, 700],
    'Sales': [1000, 1000, 1200, 900, 1000]
})
df1

   Id  Price  Sales
0   1    600   1000
1   2    720   1000
2   3    590   1200
3   4    650    900
4   5    700   1000

In [82]:
print('Mean : ', df1['Sales'].mean())
print('Sum : ', df1['Sales'].sum())
print('Min : ', df1['Sales'].min())
print('Max : ', df1['Sales'].max())
print('Count : ', df1['Sales'].count())
print('Std : ', df1['Sales'].std())
print('Median : ', df1['Sales'].median())

Mean :  1020.0
Sum :  5100
Min :  900
Max :  1200
Count :  5
Std :  109.54451150103323
Median :  1000.0

In [83]:
df1['Sales'].agg(['mean', 'min', 'max', 'sum', 'count', 'std', 'median'])

mean      1020.000000
min        900.000000
max       1200.000000
sum       5100.000000
count        5.000000
std        109.544512
median    1000.000000
Name: Sales, dtype: float64

##### mode function

In [84]:
# mode function returns the most frequently occured values in a series or a dataframe.
s = pd.Series(np.array([1, 2, 3, 2, 2, 1]), index=list('abcdef'))
s.mode()

s2 = pd.Series(np.array([1, 3, 3, 1, 2, 4]), index=list('abcdef'))
s2.mode()

0    1
1    3
dtype: int64

##### Vectorized Operations

In [85]:
# Every value will be multiplied by 10
df1 * 10

   Id  Price  Sales
0  10   6000  10000
1  20   7200  10000
2  30   5900  12000
3  40   6500   9000
4  50   7000  10000

#### Applying functions

In [86]:
def square(x):
    return x**2

In [87]:
df1['Id'].apply(square)

0     1
1     4
2     9
3    16
4    25
Name: Id, dtype: int64

In [88]:
df1['raw Id'] = df1['Id'].apply(lambda x: x**3)
df1

   Id  Price  Sales  raw Id
0   1    600   1000       1
1   2    720   1000       8
2   3    590   1200      27
3   4    650    900      64
4   5    700   1000     125