# Pandas

## Basics

In [188]:
import numpy as np
import pandas as pd

### Series

In [189]:
list1 = [10, 20, 30]
dictionary = {1:10, 2:20, 3:30}
arr = np.array([10, 20, 30])
labels = ['a', 'b', 'c']

In [190]:
pd.Series(list1)

0    10
1    20
2    30
dtype: int64

In [191]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [192]:
pd.Series(arr, labels)

a    10
b    20
c    30
dtype: int64

In [193]:
pd.Series(dictionary)

1    10
2    20
3    30
dtype: int64

### Dataframes

#### Creation

In [194]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df1 = pd.DataFrame(data)
df1

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [195]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [196]:
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns =columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

#### Selecting columns

In [197]:
print(df2["Name"])
df2[["Name", "City"]]

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

#### Creating columns

In [198]:
df2["Designation"] = ["Doctor","Eng.","Doctor","Eng."]
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

#### Removing columns

In [199]:
df2.drop("Designation", axis=1, inplace=True) # If inplace is not set to True, the deletation will only be for current code not for memory.
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

#### Removing rows

In [200]:
df2.drop(0, axis=0)

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [201]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

#### Selecting rows

In [202]:
df2.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [203]:
df2.loc[[0,2]]

    Name  Age      City  Salary
0   John   28  New York   65000
2  Peter   29    Berlin   62000

In [204]:
df2.iloc[1]

Name       Anna
Age          34
City      Paris
Salary    70000
Name: 1, dtype: object

In [ ]:
df2.loc[[1]]             # returns dataframe instead of a series

   Name  Age   City  Salary
1  Anna   34  Paris   70000

#### Selecting subsets of rows and columns

In [206]:
df2.loc[[0,1]][['Name', 'City']]

   Name      City
0  John  New York
1  Anna     Paris

#### Conditional selection

In [207]:
df2[df2['Age'] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [208]:
df2[(df2["Age"] > 30) & (df2["City"] == "Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000

### Missing Data

#### Finding missing data

In [209]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [210]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [211]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [212]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

#### Removing missing data

In [213]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [214]:
df.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

#### Filling missing data

In [215]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [216]:
values = {'A':0,'B':100,"C":300,'D':400}
df.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

### Merging, Concating, joining dataframes

#### Merging

In [217]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [218]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [219]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [220]:
pd.merge(employees, salaries)             # pd.merge(employees, salaries, on='employee_id', how='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [221]:
pd.merge(employees, salaries, on='employee_id', how='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [222]:
pd.merge(employees, salaries, on='employee_id', how='left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [223]:
pd.merge(employees, salaries, on='employee_id', how='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

#### Concating dataframes

In [224]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [225]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [226]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [227]:
pd.concat([df1, df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [228]:
pd.concat([df1, df2], axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

#### Joining dataframes

In [229]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [230]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [231]:
df2

   score
2     85
3     90
4     75

In [232]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [233]:
df1.join(df2, how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

### Group by & Aggregation

#### Group by

In [234]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [235]:
cat_group = df.groupby('Category')             # Object
cat_group

In [236]:
cat_group = df.groupby('Category')['Sales'].sum()
cat_group

Category
A    570
B    930
Name: Sales, dtype: int64

In [237]:
store_group = df.groupby('Store')['Sales'].sum()
store_group

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [238]:
combine_group = df.groupby(['Category', 'Store'])['Sales'].sum()
combine_group

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

#### Aggregation

In [239]:
df['Sales'].mean()

np.float64(187.5)

In [240]:
df['Sales'].sum()

np.int64(1500)

In [241]:
df['Sales'].min()

np.int64(100)

In [242]:
df['Sales'].max()

np.int64(300)

In [243]:
df['Sales'].count()

np.int64(8)

In [244]:
df['Sales'].std()

np.float64(66.06274074155351)

In [245]:
df['Sales'].median()

np.float64(190.0)

In [246]:
df['Sales'].agg(['mean', 'min', 'max', 'sum', 'count', 'std', 'median'])

mean       187.500000
min        100.000000
max        300.000000
sum       1500.000000
count        8.000000
std         66.062741
median     190.000000
Name: Sales, dtype: float64

### Pivot Tables and Crosstabs

#### Pivot tables

In [247]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    939     22   John  January      Q1
1  2023-01-02       B   West    854     54   Mary  January      Q1
2  2023-01-03       C  North    797     25    Bob  January      Q1
3  2023-01-04       D  South    444     89  Alice  January      Q1
4  2023-01-05       A   East    531     44   John  January      Q1
5  2023-01-06       B   West    609     76   Mary  January      Q1
6  2023-01-07       C  North    351     47    Bob  January      Q1
7  2023-01-08       D  South    349     14  Alice  January      Q1
8  2023-01-09       A   East    204     94   John  January      Q1
9  2023-01-10       B   West    387     86   Mary  January      Q1
10 2023-01-11       C  North    219     84    Bob  January      Q1
11 2023-01-12       D  South    984     61  Alice  January      Q1
12 2023-01-13       A   East    989     58   John  January      Q1
13 2023-01-14       B   West    143     15   Mary  January      Q1
14 2023-01-15       C  North    352     40    Bob  January      Q1
15 2023-01-16       D  South    873     25  Alice  January      Q1
16 2023-01-17       A   East    274     68   John  January      Q1
17 2023-01-18       B   West    811     68   Mary  January      Q1
18 2023-01-19       C  North    700     80    Bob  January      Q1
19 2023-01-20       D  South    639     64  Alice  January      Q1

In [248]:
pivot_table_1 = pd.pivot_table(data=df, values='Sales', index='Region', columns='Product')
pivot_table_1

Product      A      B      C      D
Region
East     587.4    NaN    NaN    NaN
North      NaN    NaN  483.8    NaN
South      NaN    NaN    NaN  657.8
West       NaN  560.8    NaN    NaN

In [249]:
pivot_table_2 = pd.pivot_table(data=df, values=['Sales', 'Units'], index='Region', columns='Product')
pivot_table_2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     587.4    NaN    NaN    NaN  57.2   NaN   NaN   NaN
North      NaN    NaN  483.8    NaN   NaN   NaN  55.2   NaN
South      NaN    NaN    NaN  657.8   NaN   NaN   NaN  50.6
West       NaN  560.8    NaN    NaN   NaN  59.8   NaN   NaN

#### Crosstabs

In [250]:
crosstab_1 = pd.crosstab(df['Region'], df['Product'])
crosstab_1

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

### Operations

#### Dataframes basic operations

In [251]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [252]:
df1.shape

(5, 3)

In [253]:
df1.columns

Index(['A', 'B', 'C'], dtype='str')

In [254]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [255]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [256]:
df2 = df1['A'] + 10
df2

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

#### Applying functions

In [257]:
def square(x):
    return x**2

In [258]:
df1['B'].apply(square)

0     100
1     400
2     900
3    1600
4    2500
Name: B, dtype: int64

In [259]:
df1['D'] = df1['B'].apply(square)
df1

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500

## Feature Extraction Project

### Task

#### Read anime.csv file using pandas & perform below operations on it.
* make a new column for episode count
* make a new column for time stamp
* which anime has the highest score
* give me top 5 highest scoring anime
* which anime has the highest episode count
* animes with top 5 episode count
* which is the longest running anime

### Implementation

#### Read csv file & create a dataframe

In [260]:
import numpy as np
import pandas as pd

anime_df = pd.read_csv('anime.csv')
anime_df

    Rank                                              Title  Score
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71

#### Make column for episodes count

In [261]:
def extract_episodes_count(title):
    is_eps_num = False
    ans = ""

    for i in title:
        if i == ' ' and is_eps_num:
            return int(ans)
        if is_eps_num:
            ans += i
        if i == '(':
            is_eps_num = True

In [262]:
anime_df['Episodes'] = anime_df['Title'].apply(extract_episodes_count)
anime_df.head()               # Only shows first five rows

   Rank                                              Title  Score  Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10        64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07        24
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06        13
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06        51
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05        10

#### Make column for time stamp

In [263]:
import re

time_stamp_pattern = r'[A-Za-z]{3} \d{4} - [A-Za-z]{3} \d{4}'

def extract_time_stamp(title):
    match = re.search(time_stamp_pattern, title)

    if match:
        return match.group()

In [264]:
anime_df['Time Stamp'] = anime_df['Title'].apply(extract_time_stamp)
anime_df.head()

,Rank,Title,Score,Episodes,Time Stamp
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

#### Make column for total months of time stamp

In [265]:
months_codes = {
    'jan': 1, 'feb': 2, 'mar': 3,
    'apr': 4, 'may': 5, 'jun': 6,
    'jul': 7, 'aug': 8, 'sep': 9,
    'oct': 10, 'nov': 11, 'dec': 12,
}

month_pattern = r'[a-zA-Z]{3}'
year_pattern = r'\d{4}'

In [266]:
def extract_total_months(title):
    months = re.findall(month_pattern, title)
    month_1 = months[0].lower()
    month_2 = months[1].lower()
    month_sub = months_codes[month_2] - months_codes[month_1]

    years = re.findall(year_pattern, title)
    year_1 = int(years[0])
    year_2 = int(years[1])
    year_sub = (year_2 - year_1) * 12

    return month_sub + year_sub

In [267]:
anime_df['Total Months'] = anime_df['Time Stamp'].apply(extract_total_months)
anime_df.head()

,Rank,Title,Score,Episodes,Time Stamp,Total Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,15
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,5
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,2
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,11
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,3

#### Highest score

In [268]:
anime_df[anime_df['Rank'] == 1]

,Rank,Title,Score,Episodes,Time Stamp,Total Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.1,64,Apr 2009 - Jul 2010,15

#### Top 5 highest score anime

In [269]:
anime_df[anime_df['Rank'] <= 5]

,Rank,Title,Score,Episodes,Time Stamp,Total Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,15
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,5
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,2
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,11
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,3

#### Highest episode count

In [270]:
anime_df[anime_df['Episodes'] == anime_df['Episodes'].max()]

,Rank,Title,Score,Episodes,Time Stamp,Total Months
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,47

#### Top 5 highest episodes count anime

In [276]:
highest_episodes_top_5_df = pd.DataFrame(columns=anime_df.columns)
dummy_anime_df = anime_df.copy()

for i in range(5):
    highest_episodes_top_5_df = pd.concat([highest_episodes_top_5_df, dummy_anime_df.loc[[dummy_anime_df['Episodes'].idxmax()]]])
    dummy_anime_df.drop(dummy_anime_df['Episodes'].idxmax(), inplace=True)

del dummy_anime_df
highest_episodes_top_5_df

,Rank,Title,Score,Episodes,Time Stamp,Total Months
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,47
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014,35
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,110
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002,17
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005,17

#### Longest running time